// ============================================================================
// Traduções do Painel Admin (área interna, uso da equipe). Fonte única de
// verdade para pt-BR / en / ja. O App Público usa config/traducoes.js, que é
// um arquivo separado (públicos e admin não compartilham dicionário).
//
// Uso: t('chave') ou t('chave', { var: valor }) para chaves com placeholders
// tipo {var}. Ver traduzirAdmin() no fim do arquivo.
// ============================================================================

export const IDIOMAS_ADMIN = [
  { codigo: 'pt-BR', rotulo: 'PT' },
  { codigo: 'en', rotulo: 'EN' },
  { codigo: 'ja', rotulo: '日本語' },
];

export const IDIOMA_ADMIN_PADRAO = 'pt-BR';

export const DIAS_SEMANA_ADMIN = {
  'pt-BR': ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
  en: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  ja: ['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日'],
};

export const DIAS_SEMANA_ABREV_ADMIN = {
  'pt-BR': ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
  en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  ja: ['日', '月', '火', '水', '木', '金', '土'],
};

export const LOCALE_POR_IDIOMA_ADMIN = {
  'pt-BR': 'pt-BR',
  en: 'en-US',
  ja: 'ja-JP',
};

const TEXTOS = {
  'pt-BR': {
    // Login / cadastro
    'login.tituloLogin': 'Login Admin',
    'login.tituloCadastro': 'Criar conta',
    'login.subtituloLogin': 'Entre com o e-mail e senha da sua conta.',
    'login.subtituloCadastro': 'Toda conta nova começa com acesso restrito. Peça para promoverem sua conta a acesso completo, se precisar.',
    'login.nome': 'Seu nome',
    'login.email': 'Email',
    'login.senha': 'Senha',
    'login.aguarde': 'Aguarde...',
    'login.entrar': 'Entrar',
    'login.criarConta': 'Criar conta',
    'login.esqueciSenha': 'Esqueci minha senha',
    'login.criarUmaConta': 'Criar uma conta',
    'login.jaTenhoConta': 'Já tenho conta',
    'login.voltarPublico': 'Voltar para Página Pública',
    'login.carregando': 'Carregando...',
    'login.digiteEmailPrimeiro': 'Digite seu e-mail acima primeiro, depois clique em "Esqueci minha senha".',
    'login.emailOuSenhaIncorretos': 'E-mail ou senha incorretos.',
    'login.contaCriada': 'Conta criada! Verifique seu e-mail para confirmar antes de entrar.',
    'login.linkResetEnviado': 'Enviamos um link de redefinição de senha para o seu e-mail.',

    // Sidebar
    'sidebar.adminPanel': 'Admin Panel',
    'sidebar.logadoComo': 'Logado como:',
    'sidebar.acesso': 'Acesso:',
    'sidebar.acessoCompleto': 'Completo',
    'sidebar.acessoRestrito': 'Restrito',
    'sidebar.logout': '🚪 Sair',

    // Nav
    'nav.dashboard': '📊 Dashboard',
    'nav.agendamentos': '📅 Agendamentos',
    'nav.clientes': '👥 Clientes',
    'nav.profissionais': '💈 Profissionais',
    'nav.caixa': '💰 Caixa',
    'nav.comandas': '📋 Comandas',
    'nav.fidelidade': '🎁 Fidelidade',
    'nav.ordem': '📍 Ordem de Chegada',
    'nav.aniversariantes': '🎂 Aniversariantes',
    'nav.cadastros': '🗂️ Cadastros',
    'nav.reincidentes': '⚠️ Reincidentes',
    'nav.mais': 'Mais',
    'nav.agendaCurta': 'Agenda',
    'nav.clientesCurta': 'Clientes',

    // Comum (compartilhado entre páginas)
    'comum.salvar': 'Salvar',
    'comum.salvando': 'Salvando...',
    'comum.cancelar': 'Cancelar',
    'comum.adicionar': 'Adicionar',
    'comum.deletar': 'Deletar',
    'comum.remover': 'Remover',
    'comum.editar': 'Editar',
    'comum.carregando': '⏳ Carregando...',
    'comum.acao': 'Ação',
    'comum.acoes': 'Ações',
    'comum.status': 'Status',
    'comum.data': 'Data',
    'comum.hora': 'Hora',
    'comum.cliente': 'Cliente',
    'comum.servico': 'Serviço',
    'comum.profissional': 'Profissional',
    'comum.email': 'Email',
    'comum.telefone': 'Telefone',
    'comum.valor': 'Valor',
    'comum.total': 'Total',
    'comum.detalhes': 'Detalhes',
    'comum.ocultar': 'Ocultar',
    'comum.confirmar': 'Confirmar',
    'comum.selecioneServico': 'Selecione um serviço',
    'comum.selecioneProfissional': 'Selecione um profissional',
    'comum.aberto': 'Aberto',
    'comum.fechado': 'Fechado',

    // Status de agendamento (mostrados na tela; valor gravado no banco continua o mesmo)
    'statusAg.AGENDADO': 'Agendado',
    'statusAg.CONFIRMADO': 'Confirmado',
    'statusAg.REALIZADO': 'Realizado',
    'statusAg.CANCELADO': 'Cancelado',
    'statusAg.NÃO_COMPARECEU': 'Não compareceu',
    'statusAg.PREÇO_PENDENTE': 'Preço pendente',
    'statusAg.todos': 'Todos os Status',

    // Dashboard
    'dashboard.titulo': '📊 Dashboard',
    'dashboard.carregando': '⏳ Carregando dashboard...',
    'dashboard.totalAgendamentos': '📅 Total Agendamentos',
    'dashboard.todosStatus': 'Todos os status',
    'dashboard.confirmados': '✅ Confirmados',
    'dashboard.aguardando': 'Aguardando',
    'dashboard.realizados': '✓ Realizados',
    'dashboard.completados': 'Completados',
    'dashboard.receitaTotal': '💰 Receita Total',
    'dashboard.deServicosRealizados': 'De serviços realizados',
    'dashboard.clientes': '👥 Clientes',
    'dashboard.cadastrados': 'Cadastrados',
    'dashboard.agendamentosPorStatus': 'Agendamentos por Status',
    'dashboard.agendamentosPorProfissional': 'Agendamentos por Profissional',
    'dashboard.receita7Dias': 'Receita - Últimos 7 Dias',
    'dashboard.receitaLegenda': 'Receita (¥)',
    'dashboard.agendamentosRecentes': 'Agendamentos Recentes',
    'dashboard.erroBuscarDados': '❌ Erro ao buscar dados: {msg}',

    // Agendamentos
    'agendamentos.titulo': '📅 Agendamentos',
    'agendamentos.novoAgendamento': 'Novo Agendamento',
    'agendamentos.nomeCliente': 'Nome do Cliente',
    'agendamentos.emailCliente': 'Email do Cliente',
    'agendamentos.emailClienteOpcional': 'Email do Cliente (opcional)',
    'agendamentos.telefoneOpcional': 'Telefone',
    'agendamentos.modoEncaixe': '🔀 Modo Encaixe',
    'agendamentos.modoEncaixeAtivado': '(ativado — permite sobrepor outro horário)',
    'agendamentos.selecioneParaVerHorarios': 'Selecione serviço, profissional e data para ver os horários.',
    'agendamentos.conflito': '⚠️ Conflito:',
    'agendamentos.jaOcupadoNesseDia': 'Já ocupado nesse dia: {lista}',
    'agendamentos.nenhumHorarioLivre': 'Nenhum horário livre nesse dia para esse profissional/serviço. Ative o Modo Encaixe para forçar um horário.',
    'agendamentos.agendar': 'Agendar',
    'agendamentos.calendario': '📅 Calendário - {nome}',
    'agendamentos.anterior': '← Anterior',
    'agendamentos.proximo': 'Próximo →',
    'agendamentos.listaDetalhada': '📋 Lista Detalhada',
    'agendamentos.totalAgendamentos': 'Total: {n} agendamentos',
    'agendamentos.nenhumEncontrado': 'Nenhum agendamento encontrado',
    'agendamentos.diaSemana': 'Dia da Semana',
    'agendamentos.preco': 'Preço (¥)',
    'agendamentos.encaixeTag': '🔀 encaixe',
    'agendamentos.criadoComoEncaixe': 'Criado como encaixe',
    'agendamentos.confirmarDeletar': 'Tem certeza que deseja deletar este agendamento?',
    'agendamentos.preencherObrigatorios': '⚠️ Preencha todos os campos obrigatórios!',
    'agendamentos.horarioIndisponivel': '⚠️ Esse horário não está mais disponível. Escolha outro na lista, ou ative o modo Encaixe para forçar mesmo assim.',
    'agendamentos.confirmarEncaixe': '⚠️ ENCAIXE: este horário ({horario}) invade o(s) seguinte(s) agendamento(s) de {prof}:\n\n{resumo}\n\nAo confirmar, você assume a responsabilidade por resolver esse conflito com os clientes. Continuar?',
    'agendamentos.criadoComSucesso': '✅ Agendamento criado com sucesso!',
    'agendamentos.erroAoCriar': '❌ Erro ao criar agendamento: {msg}',
    'agendamentos.statusAtualizado': '✅ Status atualizado!',
    'agendamentos.erroAtualizarStatus': '❌ Erro ao atualizar status: {msg}',
    'agendamentos.deletado': '✅ Agendamento deletado!',
    'agendamentos.erroDeletar': '❌ Erro ao deletar: {msg}',
    'agendamentos.erroBuscar': '❌ Erro ao buscar agendamentos: {msg}',
    'agendamentos.desconhecido': 'Desconhecido',
    'agendamentos.agendamentosDoDia': 'Agendamentos de {data}',
    'agendamentos.nenhumAgendamentoNoDia': 'Nenhum agendamento nesse dia.',
    'agendamentos.fecharModal': 'Fechar',
    'agendamentos.bloquearHorario': 'Bloquear Horário',
    'agendamentos.bloquearHorarioDescricao': 'Marque um período em que o profissional não vai atender (consulta médica, folga, etc.) — esse período fica indisponível para novos agendamentos.',
    'agendamentos.motivoOpcional': 'Motivo (opcional)',
    'agendamentos.criarBloqueio': 'Bloquear',
    'agendamentos.bloqueioCriado': 'Horário bloqueado com sucesso!',
    'agendamentos.erroCriarBloqueio': 'Erro ao bloquear horário: {msg}',
    'agendamentos.horarioFimAntesInicio': 'O horário final deve ser depois do horário inicial.',
    'agendamentos.confirmarDeletarBloqueio': 'Tem certeza que deseja remover este bloqueio?',
    'agendamentos.bloqueioDeletado': 'Bloqueio removido.',
    'agendamentos.erroDeletarBloqueio': 'Erro ao remover bloqueio: {msg}',
    'agendamentos.bloqueiosAtivos': 'Bloqueios agendados',
    'agendamentos.bloqueioTag': 'Bloqueado',
    'agendamentos.dataInicioLabel': 'Data inicial',
    'agendamentos.dataFimOpcionalLabel': 'Data final (opcional, para períodos)',
    'agendamentos.diaInteiroLabel': 'Fechar o dia todo (feriado, folga completa)',
    'agendamentos.diaTodo': 'Fechado (dia todo)',
    'agendamentos.bloqueioCriadoPeriodo': '{n} dias bloqueados com sucesso!',
    'agendamentos.dataFimAntesInicio': 'A data final deve ser depois (ou igual) da data inicial.',
    'agendamentos.editarTooltip': 'Clique para editar data/horário',
    'agendamentos.editarAgendamento': 'Editar Agendamento',
    'agendamentos.editarAgendamentoAviso': 'Ao salvar, o cliente e o profissional recebem um e-mail automático avisando da mudança de horário.',
    'agendamentos.salvarAlteracao': 'Salvar alteração',
    'agendamentos.alteracaoSalva': 'Horário alterado! Cliente e profissional foram notificados por e-mail.',
    'agendamentos.erroSalvarAlteracao': 'Erro ao salvar alteração: {msg}',
    'agendamentos.subDia': 'Dia',
    'agendamentos.subSemana': 'Semana',
    'agendamentos.subMes': 'Mês',
    'agendamentos.subLista': 'Lista',
    'agendamentos.subBloqueios': 'Bloqueios',
    'agendamentos.livre': 'Livre',
    'agendamentos.salaoFechadoNesseDia': 'O salão está fechado nesse dia.',
    'agendamentos.salaoFechadoNaSemana': 'O salão está fechado a semana toda nesse período.',
    'agendamentos.fechado': 'Fechado',
    'agendamentos.novoBtnFlutuante': 'Novo agendamento',
    'agendamentos.escolhaData': 'Escolha a data',
    'agendamentos.dataNascimento': 'Data de Nascimento (opcional)',

    // Tela de Detalhes do Agendamento
    'agendamentos.verDetalhesTooltip': 'Toque para ver detalhes do agendamento',
    'agendamentos.detalhesAgendamento': 'Detalhes do Agendamento',
    'agendamentos.valor': 'Valor',
    'agendamentos.duracao': 'Duração',
    'agendamentos.duracaoMinutosSufixo': '{n} min',
    'agendamentos.duracaoInvalida': '⚠️ Informe uma duração válida em minutos.',
    'agendamentos.dataHoraLabel': 'Data/Hora',
    'agendamentos.criadoEm': 'Criado em',
    'agendamentos.notas': 'Observações',
    'agendamentos.notasPlaceholder': 'Anotações rápidas sobre este atendimento...',
    'agendamentos.salvarNotas': 'Salvar observações',
    'agendamentos.notasSalvas': '✅ Observações salvas!',
    'agendamentos.statusConfirmado': 'Confirmado',
    'agendamentos.statusPreferencia': 'Preferência (cliente pediu este profissional)',
    'agendamentos.statusAusente': 'Ausente (não compareceu)',
    'agendamentos.enviarLembrete': '📱 Enviar Lembrete por WhatsApp',
    'agendamentos.semTelefoneParaLembrete': '⚠️ Este cliente não tem telefone cadastrado.',
    'agendamentos.mensagemLembrete': 'Olá {nome}! Passando para lembrar do seu horário no Kaizen Barber Shop no dia {data} às {hora} ({servico}). Até lá! 💈',
    'agendamentos.prontuario': '📋 Prontuário (histórico de atendimentos)',
    'agendamentos.prontuarioTitulo': 'Prontuário do Cliente',
    'agendamentos.prontuarioVazio': 'Nenhum atendimento realizado ainda.',
    'agendamentos.anamnese': '📝 Anamnese (avaliação capilar)',
    'agendamentos.anamneseTitulo': 'Anamnese do Cliente',
    'agendamentos.anamnesePlaceholder': 'Histórico capilar, alergias, preferências, observações da avaliação...',
    'agendamentos.salvarAnamnese': 'Salvar anamnese',
    'agendamentos.anamneseSalva': '✅ Anamnese salva!',
    'agendamentos.alterarParaEncaixe': '🔀 Alterar para Encaixe',
    'agendamentos.jaEhEncaixe': 'Este agendamento já está marcado como encaixe.',
    'agendamentos.confirmarAlterarEncaixe': 'Marcar este agendamento como Encaixe (fora da agenda padrão)?',
    'agendamentos.encaixeConvertidoTag': 'Convertido para encaixe pelo Admin.',
    'agendamentos.erroSalvarCampo': '❌ Erro ao salvar: {msg}',
    'agendamentos.deletarAgendamento': '🗑️ Deletar Agendamento',

    // Cancelamento com motivo
    'agendamentos.cancelarAgendamento': '🚫 Cancelar Agendamento',
    'agendamentos.quemCancelou': 'Quem cancelou?',
    'agendamentos.canceladoPor.cliente': 'Cliente',
    'agendamentos.canceladoPor.barbearia': 'Barbearia',
    'agendamentos.canceladoPorLabel': 'Cancelado por {quem}',
    'agendamentos.motivoCancelamento': 'Motivo do cancelamento',
    'agendamentos.motivoCancelamentoPlaceholder': 'Ex: cliente teve um imprevisto de última hora...',
    'agendamentos.motivoCancelamentoObrigatorio': '⚠️ Descreva o motivo do cancelamento antes de confirmar.',
    'agendamentos.confirmarCancelamento': 'Confirmar cancelamento',
    'agendamentos.cancelado': '✅ Agendamento cancelado.',
    'agendamentos.erroCancelar': '❌ Erro ao cancelar: {msg}',
    'agendamentos.avisoReincidenciaExplicacao': 'Como faltam menos de 2h pro horário, isso conta como cancelamento de última hora — o cliente vai aparecer na tela Reincidentes (menu Mais).',
    'agendamentos.avisoReincidencia': '⚠️ Atenção: {nome} já teve {n} cancelamento(s) de última hora. Veja a tela Reincidentes (menu Mais) para decidir se vale continuar atendendo.',

    'menu.titulo': 'Menu',

    // Clientes
    'clientes.titulo': '👥 Clientes',
    'clientes.novoCliente': 'Novo Cliente',
    'clientes.nomeCliente': 'Nome do Cliente',
    'clientes.adicionarCliente': 'Adicionar Cliente',
    'clientes.listaClientes': 'Lista de Clientes',
    'clientes.nenhumCadastrado': 'Nenhum cliente cadastrado ainda',
    'clientes.totalClientes': 'Total: {n} clientes',
    'clientes.nome': 'Nome',
    'clientes.primeiraVisita': 'Primeira Visita',
    'clientes.totalAgendamentos': 'Total Agendamentos',
    'clientes.confirmados': 'Confirmados',
    'clientes.bloqueado': 'Bloqueado',
    'clientes.nomeEmailObrigatorios': '⚠️ Nome e telefone são obrigatórios!',
    'clientes.dataNascimento': 'Data de Nascimento (opcional)',
    'clientes.emailOpcional': 'Email (opcional)',
    'clientes.adicionadoComSucesso': '✅ Cliente adicionado com sucesso!',
    'clientes.confirmarDeletar': 'Tem certeza que deseja deletar este cliente? Seus agendamentos também serão deletados!',
    'clientes.deletado': '✅ Cliente deletado!',
    'clientes.erroBuscar': '❌ Erro ao buscar clientes: {msg}',
    'clientes.erroAdicionar': '❌ Erro ao adicionar cliente: {msg}',
    'clientes.erroDeletar': '❌ Erro ao deletar cliente: {msg}',
    'clientes.editarCliente': 'Editar Cliente',
    'clientes.editadoComSucesso': '✅ Cliente atualizado com sucesso!',
    'clientes.erroEditar': '❌ Erro ao atualizar cliente: {msg}',
    'clientes.mensagemWhatsapp': 'Olá {nome}! Tudo bem? Aqui é do Kaizen Barber Shop. 💈',
    'clientes.buscarPlaceholder': 'Buscar cliente por nome...',
    'clientes.nenhumEncontradoBusca': 'Nenhum cliente encontrado com esse nome.',

    // Profissionais
    'profissionais.horarioSalao': '🕒 Horário do Salão',
    'profissionais.horarioSalaoDesc': 'Todos os profissionais seguem este horário por padrão. Ele é a fonte única usada tanto aqui quanto na agenda pública dos clientes.',
    'profissionais.almoco': 'Almoço:',
    'profissionais.almocoTodosDias': '(todos os dias de funcionamento)',
    'profissionais.horarioEstendido': '📅 Horário Estendido (feriados)',
    'profissionais.horarioEstendidoDesc': 'Use em feriados prolongados (ex: Golden Week, Obon, Ano Novo), quando os profissionais — como o Gabriel, que já costuma abrir mais cedo durante a semana — atendem a partir de um horário diferente do padrão. Enquanto ativo, o horário de abertura abaixo vale para TODOS os profissionais, nas datas escolhidas. O fechamento e o almoço não mudam.',
    'profissionais.ativado': 'Ativado',
    'profissionais.desativado': 'Desativado',
    'profissionais.abertura': 'Abertura',
    'profissionais.dataInicio': 'Data início',
    'profissionais.dataFim': 'Data fim',
    'profissionais.preencherDatas': 'Preencha a data de início e fim antes de ativar.',
    'profissionais.salvo': 'Salvo! A agenda pública já está usando esse horário.',
    'profissionais.erroSalvarHorario': 'Não consegui salvar. Confira se a tabela configuracoes_horario existe no Supabase.',
    'profissionais.novoProfissional': 'Novo Profissional',
    'profissionais.novoProfissionalDesc': 'Isso só adiciona um card visual aqui. Para o profissional aparecer de verdade na agenda pública e no Admin (com horários, comissão etc.), é preciso cadastrá-lo no Supabase e em config/profissionais.js.',
    'profissionais.nomeProfissional': 'Nome do Profissional',
    'profissionais.especialidadesPlaceholder': 'Especialidades (ex: Cortes, Barba)',
    'profissionais.adicionarProfissional': 'Adicionar Profissional',
    'profissionais.horarioLabel': 'Horário:',
    'profissionais.segueHorarioSalao': 'segue o horário do salão (acima)',
    'profissionais.comissao': 'Comissão:',
    'profissionais.salvarComissao': 'Salvar Comissão',
    'profissionais.comissaoNaoSalvo': '(não salvo — cadastro só visual)',
    'profissionais.digiteNumeroValido': 'Digite um número entre 0 e 100.',
    'profissionais.comissaoSalva': 'Salvo!',
    'profissionais.erroSalvarComissao': 'Não consegui salvar. Confira se a coluna comissao_percentual existe na tabela profissionais.',

    // Caixa
    'caixa.titulo': 'Caixa - {dia}, {data}',
    'caixa.carregando': '⏳ Carregando caixa...',
    'caixa.statusCaixa': 'Status do Caixa',
    'caixa.aberto': '✅ ABERTO',
    'caixa.fechado': '❌ FECHADO',
    'caixa.saldoInicialPlaceholder': 'Saldo Inicial (¥)',
    'caixa.reabrirCaixa': 'Reabrir Caixa',
    'caixa.abrirCaixa': 'Abrir Caixa',
    'caixa.fecharCaixa': 'Fechar Caixa',
    'caixa.resumoDia': 'Resumo do Dia',
    'caixa.saldoInicial': 'Saldo Inicial:',
    'caixa.entradas': 'Entradas:',
    'caixa.saidas': 'Saídas:',
    'caixa.saldoFinal': 'Saldo Final:',
    'caixa.novaMovimentacao': 'Nova Movimentação Manual',
    'caixa.entrada': 'Entrada',
    'caixa.saida': 'Saída',
    'caixa.descricaoPlaceholder': 'Descrição',
    'caixa.valorPlaceholder': 'Valor (¥)',
    'caixa.movimentacoesHoje': 'Movimentações de Hoje',
    'caixa.nenhumaMovimentacao': 'Nenhuma movimentação ainda hoje',
    'caixa.tipo': 'Tipo',
    'caixa.descricao': 'Descrição',
    'caixa.entradaTag': '➕ Entrada',
    'caixa.saidaTag': '➖ Saída',
    'caixa.comanda': '(comanda)',
    'caixa.historicoDias': '📅 Histórico de Dias (últimos 90 dias)',
    'caixa.nenhumDiaRegistrado': 'Nenhum dia de caixa registrado ainda',
    'caixa.semMovimentacoesNesseDia': 'Sem movimentações neste dia.',
    'caixa.movimentoMes': '📆 Movimento do Mês',
    'caixa.movimentoLiquido': 'Movimento Líquido:',
    'caixa.comissaoPorProfissional': '💈 Comissão por Profissional',
    'caixa.semanaAtual': 'Semana atual ({inicio} a {fim})',
    'caixa.mesSelecionado': 'Mês selecionado ({mes})',
    'caixa.faturado': 'Faturado',
    'caixa.comissaoPercentual': 'Comissão %',
    'caixa.comissaoDevida': 'Comissão Devida',
    'caixa.comissaoDefinidaEm': 'A comissão % de cada profissional é definida na aba Profissionais.',
    'caixa.confirmarFechar': 'Fechar o caixa de hoje? Depois disso não será possível fechar novas comandas hoje sem reabrir.',
    'caixa.confirmarRemoverMov': 'Remover esta movimentação manual do caixa?',
    'caixa.erroCarregar': '❌ Erro ao carregar o caixa: {msg}',
    'caixa.erroCarregarMes': '❌ Erro ao carregar o mês: {msg}',
    'caixa.erroAbrir': '❌ Erro ao abrir caixa: {msg}',
    'caixa.erroFechar': '❌ Erro ao fechar caixa: {msg}',
    'caixa.erroAdicionarMov': '❌ Erro ao adicionar movimentação: {msg}',
    'caixa.erroRemoverMov': '❌ Erro ao remover: {msg}',

    // Comandas
    'comandas.titulo': '📋 Comandas do Dia - {dia}, {data}',
    'comandas.statusCaixa': 'Status do Caixa',
    'comandas.abraCaixaAviso': 'Abra o caixa na aba Caixa para poder fechar comandas ou lançar atendimentos avulsos.',
    'comandas.totalRealizadoHoje': 'Total Realizado Hoje',
    'comandas.atendimentos': 'Atendimentos:',
    'comandas.comandasAbertas': '🕓 Comandas Abertas (agendamentos de hoje)',
    'comandas.nenhumaComandaAberta': 'Nenhuma comanda aberta para hoje',
    'comandas.fechar': '✅ Fechar',
    'comandas.lancarAvulso': 'Lançar Atendimento Avulso',
    'comandas.adicionarServico': 'Adicionar Serviço',
    'comandas.selecioneProfissional': 'Selecione profissional',
    'comandas.servicosRealizadosHoje': '📊 Serviços Realizados Hoje',
    'comandas.nenhumRealizadoAinda': 'Nenhum serviço realizado ainda hoje',
    'comandas.jaLancadosNoCaixa': 'Já lançados no caixa do dia — para corrigir um valor, ajuste diretamente na aba Caixa.',
    'comandas.caixaNaoAberto': '⚠️ O caixa de hoje ainda não foi aberto. Vá na aba Caixa e abra o caixa antes de fechar comandas.',
    'comandas.caixaNaoAbertoAvulso': '⚠️ O caixa de hoje ainda não foi aberto. Vá na aba Caixa e abra o caixa antes de lançar atendimentos avulsos.',
    'comandas.fecharPrompt': 'Fechar "{servico}" de {cliente} ({profissional}).\nValor final (¥):',
    'comandas.valorInvalido': '⚠️ Valor inválido.',
    'comandas.fechadaComSucesso': '✅ Comanda fechada e lançada no caixa!',
    'comandas.erroFechar': '❌ Erro ao fechar comanda: {msg}',
    'comandas.preencherTodosCampos': '⚠️ Preencha todos os campos!',
    'comandas.servicoOuProfInvalido': '⚠️ Serviço ou profissional inválido.',
    'comandas.lancadaComSucesso': '✅ Atendimento lançado na comanda e no caixa!',
    'comandas.erroAdicionar': '❌ Erro ao adicionar: {msg}',
    'comandas.erroBuscar': '❌ Erro ao buscar comandas: {msg}',

    // Fidelidade
    'fidelidade.titulo': '🎁 Programa de Fidelidade',
    'fidelidade.totalPontos': '📊 Total de Pontos',
    'fidelidade.emTodaBase': 'Em toda base de clientes',
    'fidelidade.clientesAtivos': '👥 Clientes Ativos',
    'fidelidade.comAgendamentos': 'Com agendamentos',
    'fidelidade.descontosResgatados': '💰 Descontos Resgatados',
    'fidelidade.valorTotalResgatado': 'Valor total resgatado',
    'fidelidade.regrasPrograma': 'ℹ️ Regras do Programa',
    'fidelidade.regra1': '✅ 2 pontos por serviço realizado',
    'fidelidade.regra2': '✅ 10 pontos = ¥500 desconto',
    'fidelidade.regra3': '✅ Válido por 3 meses',
    'fidelidade.regra4': '✅ Intransferível',
    'fidelidade.clientesSaldoPontos': '👥 Clientes - Saldo de Pontos',
    'fidelidade.buscarClientePlaceholder': 'Buscar cliente por nome...',
    'fidelidade.nenhumEncontrado': 'Nenhum cliente encontrado',
    'fidelidade.dataInscricao': 'Data Inscrição',
    'fidelidade.agendamentos': 'Agendamentos',
    'fidelidade.pontosDisponiveis': 'Pontos Disponíveis',
    'fidelidade.pontosResgatar': 'Pontos a Resgatar',
    'fidelidade.descontoIene': 'Desconto (¥)',
    'fidelidade.ativo': '✅ Ativo',
    'fidelidade.semPontos': '⚪ Sem pontos',
    'fidelidade.comoFunciona': '📋 Como Funciona o Programa',
    'fidelidade.objetivo': '🎯 Objetivo:',
    'fidelidade.objetivoTexto': 'Recompensar clientes fiéis com descontos em serviços futuros',
    'fidelidade.pontosLabel': '⭐ Pontos:',
    'fidelidade.pontosTexto': 'Cliente ganha 2 pontos para cada serviço realizado',
    'fidelidade.resgate': '💳 Resgate:',
    'fidelidade.resgateTexto': 'A cada 10 pontos acumulados, cliente ganha ¥500 de desconto',
    'fidelidade.validade': '⏰ Validade:',
    'fidelidade.validadeTexto': 'Pontos são válidos por 3 meses a partir da data do serviço',
    'fidelidade.intransferivel': '🔒 Intransferível:',
    'fidelidade.intransferivelTexto': 'Pontos não podem ser transferidos entre clientes',
    'fidelidade.rastreamento': '📊 Rastreamento:',
    'fidelidade.rastreamentoTexto': 'Cliente pode ver seu saldo na página de fidelidade',
    'fidelidade.erroBuscar': '❌ Erro ao buscar clientes: {msg}',

    // Ordem de Chegada
    'ordem.titulo': 'Ordem de Chegada',
    'ordem.bloqueioAtivoHoje': '🚫 Bloqueio Ativo Hoje',
    'ordem.motivo': 'Motivo:',
    'ordem.tipo': 'Tipo:',
    'ordem.diaInteiro': 'Dia Inteiro',
    'ordem.periodo': 'Período',
    'ordem.agendamentosBloqueados': '⚠️ Agendamentos bloqueados! Apenas ordem de chegada.',
    'ordem.bloquearDiaPeriodo': 'Bloquear Dia/Período',
    'ordem.periodoManha': 'Período (Manhã)',
    'ordem.periodoTarde': 'Período (Tarde)',
    'ordem.periodoNoite': 'Período (Noite)',
    'ordem.motivoPlaceholder': 'Motivo (ex: Feriado, Festival, Movimento Alto)',
    'ordem.bloquear': 'Bloquear',
    'ordem.diasBloqueados': 'Dias Bloqueados',
    'ordem.diaInteiroTag': '📅 Dia Inteiro',
    'ordem.periodoTag': '🕐 Período',
    'ordem.ativo': '🔒 Ativo',
    'ordem.inativo': 'Inativo',
    'ordem.registrarChegada': 'Registrar Chegada',
    'ordem.nomeCliente': 'Nome do Cliente',
    'ordem.selecioneServico': 'Selecione serviço',
    'ordem.filaEspera': 'Fila de Espera (Ordem de Chegada)',
    'ordem.ordem': 'Ordem',
    'ordem.horarioChegada': 'Horário de Chegada',
    'ordem.atendendo': '✅ Atendendo',
    'ordem.atendido': '✔️ Atendido',
    'ordem.aguardando': '⏳ Aguardando',
    'ordem.atender': 'Atender',
    'ordem.finalizar': 'Finalizar',

    // Aniversariantes
    'aniversariantes.titulo': '🎂 Aniversariantes',
    'aniversariantes.aniversariantesDoMes': 'Aniversariantes deste mês',
    'aniversariantes.proximos': 'Próximos aniversários',
    'aniversariantes.nenhumEsteMes': 'Nenhum cliente com aniversário este mês (com data cadastrada).',
    'aniversariantes.nenhumCadastrado': 'Nenhum cliente com data de nascimento cadastrada ainda.',
    'aniversariantes.hoje': '🎉 Hoje!',
    'aniversariantes.diasFaltam': 'em {n} dias',
    'aniversariantes.amanha': 'amanhã',
    'aniversariantes.descontoDisponivel': '🎁 Desconto de 40% disponível até {data}',
    'aniversariantes.marcarUsado': 'Marcar desconto como usado',
    'aniversariantes.confirmarUsarDesconto': 'Marcar o desconto de aniversário deste cliente como já usado?',
    'aniversariantes.erroBuscar': '❌ Erro ao buscar aniversariantes: {msg}',
    'aniversariantes.erroAtualizar': '❌ Erro ao atualizar: {msg}',
    'aniversariantes.comoFunciona': 'ℹ️ Todo dia, o sistema confere quem faz aniversário e manda um e-mail automático de parabéns pro cliente, avisando do desconto de 40% (válido por 30 dias). Quando o cliente voltar, aplique os 40% na hora de fechar a comanda e depois clique em "marcar como usado" aqui.',

    // Reincidentes (cancelamentos de última hora)
    'reincidentes.titulo': '⚠️ Clientes Reincidentes',
    'reincidentes.comoFunciona': 'ℹ️ Aqui aparece todo cliente que já teve um cancelamento de última hora (menos de 2h de antecedência) registrado pelo Admin. A partir de {n} ocorrências o card fica destacado em vermelho — um sinal pra você avaliar se vale a pena continuar atendendo. O botão "Bloquear" só marca um selo de aviso; ainda não impede um novo agendamento sozinho.',
    'reincidentes.nenhum': 'Nenhum cliente reincidente até agora. 🎉',
    'reincidentes.ocorrencias': '{n} cancelamento(s) de última hora',
    'reincidentes.bloqueado': 'Bloqueado',
    'reincidentes.bloquear': 'Bloquear cliente',
    'reincidentes.desbloquear': 'Desbloquear cliente',
    'reincidentes.confirmarBloquear': 'Marcar {nome} como bloqueado?',
    'reincidentes.confirmarDesbloquear': 'Remover o bloqueio de {nome}?',
    'reincidentes.erroAtualizar': '❌ Erro ao atualizar: {msg}',

    // Notificações em tempo real (toast + push)
    'notificacoes.novoAgendamento': 'Novo agendamento',
    'notificacoes.novoAgendamentoCorpo': '{cliente} marcou {servico} às {hora} com {profissional}.',
    'notificacoes.agendamentoCancelado': 'Agendamento cancelado',
    'notificacoes.agendamentoCanceladoCorpo': '{cliente} cancelou {servico} às {hora} com {profissional}.',
    'notificacoes.ativarSom': 'Ativar som das notificações',
    'notificacoes.desativarSom': 'Silenciar notificações',
    'notificacoes.push.titulo': 'Notificações no celular',
    'notificacoes.push.descricao': 'Receba um aviso no celular sempre que alguém agendar ou cancelar um horário, mesmo com o app fechado.',
    'notificacoes.push.ativar': 'Ativar notificações neste dispositivo',
    'notificacoes.push.ativando': 'Ativando...',
    'notificacoes.push.ativado': '✅ Notificações ativadas neste dispositivo.',
    'notificacoes.push.desativar': 'Desativar neste dispositivo',
    'notificacoes.push.naoSuportado': 'Este navegador não suporta notificações push.',
    'notificacoes.push.permissaoNegada': '⚠️ Você bloqueou as notificações para este site. Ative nas configurações do navegador/celular.',
    'notificacoes.push.erro': '❌ Erro ao ativar notificações: {msg}',

    // Cadastros (Serviços / Produtos / Pacotes)
    'cadastros.titulo': '🗂️ Cadastros',
    'cadastros.servicos.titulo': 'Serviços',
    'cadastros.servicos.subtitulo': 'Cadastre serviços e disponibilize para agendamentos',
    'cadastros.produtos.titulo': 'Produtos',
    'cadastros.produtos.subtitulo': 'Confira seus produtos e a quantidade em estoque',
    'cadastros.pacotes.titulo': 'Pacotes',
    'cadastros.pacotes.subtitulo': 'Visualize suas vendas de pacotes',
    'cadastros.pacotes.meusPacotes': 'Meus Pacotes',
    'cadastros.pacotes.meusPacotesSubtitulo': 'Pacotes disponíveis para venda',
    'cadastros.pacotes.vendaPacotes': 'Venda de Pacotes',
    'cadastros.pacotes.vendaPacotesSubtitulo': 'Histórico de pacotes vendidos aos clientes',
    'cadastros.buscarPlaceholder': 'Pesquise pelo nome',
    'cadastros.novoServico': 'Novo Serviço',
    'cadastros.novoProduto': 'Novo Produto',
    'cadastros.novoPacote': 'Novo Pacote',
    'cadastros.registrarVenda': 'Registrar Venda',
    'cadastros.novoItem': 'Novo Registro',
    'cadastros.editarItem': 'Editar Registro',
    'cadastros.nomeCampo': 'Nome',
    'cadastros.descricaoCampo': 'Descrição',
    'cadastros.precoCampo': 'Preço (¥)',
    'cadastros.duracaoCampo': 'Duração (minutos)',
    'cadastros.estoqueCampo': 'Quantidade em estoque',
    'cadastros.sessoesCampo': 'Quantidade de sessões (deixe em branco = ilimitado)',
    'cadastros.validadeCampo': 'Validade (dias)',
    'cadastros.clienteCampo': 'Nome do Cliente',
    'cadastros.sessoesRestantesCampo': 'Sessões restantes (deixe em branco = ilimitado)',
    'cadastros.ativoCampo': 'Ativo',
    'cadastros.nomeObrigatorio': '⚠️ Preencha o nome antes de salvar.',
    'cadastros.confirmarRemover': 'Tem certeza que deseja remover este registro?',
    'cadastros.nenhumEncontrado': 'Nenhum resultado encontrado.',
    'cadastros.inativo': 'inativo',
    'cadastros.semEstoque': 'Sem estoque',
    'cadastros.estoqueUnidades': '{n} em estoque',
    'cadastros.sessoesIlimitadas': 'Ilimitado',
    'cadastros.sessoesRestantesLabel': '{n} sessões',
    'cadastros.validadeDiasLabel': 'validade {n} dias',
    'cadastros.imagemCampo': 'Imagem ilustrativa',
    'cadastros.erroCarregarServicos': '❌ Erro ao carregar serviços: {msg}',
    'cadastros.servicoSalvo': '✅ Serviço salvo! Já aparece no site público e na Agenda.',
    'cadastros.erroSalvarServico': '❌ Erro ao salvar serviço: {msg}',
    'cadastros.confirmarDesativarServico': 'Desativar este serviço? Ele deixa de aparecer no site público e no Admin, mas o histórico de agendamentos já feitos com ele é mantido.',
    'cadastros.confirmarReativarServico': 'Reativar este serviço? Ele volta a aparecer no site público e no Admin.',
    'cadastros.erroCarregarProdutos': '❌ Erro ao carregar produtos: {msg}',
    'cadastros.produtoSalvo': '✅ Produto salvo!',
    'cadastros.erroSalvarProduto': '❌ Erro ao salvar produto: {msg}',
    'cadastros.confirmarDesativarProduto': 'Desativar este produto? Ele fica marcado como indisponível.',
    'cadastros.confirmarReativarProduto': 'Reativar este produto?',
    'cadastros.erroCarregarPacotes': '❌ Erro ao carregar pacotes: {msg}',
    'cadastros.pacoteSalvo': '✅ Pacote salvo! Já aparece no site público.',
    'cadastros.erroSalvarPacote': '❌ Erro ao salvar pacote: {msg}',
    'cadastros.confirmarDesativarPacote': 'Desativar este pacote? Ele deixa de aparecer no site público.',
    'cadastros.confirmarReativarPacote': 'Reativar este pacote? Ele volta a aparecer no site público.',
  },

  en: {
    'login.tituloLogin': 'Admin Login',
    'login.tituloCadastro': 'Create account',
    'login.subtituloLogin': 'Sign in with your account email and password.',
    'login.subtituloCadastro': 'Every new account starts with restricted access. Ask to have your account upgraded to full access if needed.',
    'login.nome': 'Your name',
    'login.email': 'Email',
    'login.senha': 'Password',
    'login.aguarde': 'Please wait...',
    'login.entrar': 'Sign in',
    'login.criarConta': 'Create account',
    'login.esqueciSenha': 'Forgot my password',
    'login.criarUmaConta': 'Create an account',
    'login.jaTenhoConta': 'I already have an account',
    'login.voltarPublico': 'Back to Public Site',
    'login.carregando': 'Loading...',
    'login.digiteEmailPrimeiro': 'Enter your email above first, then click "Forgot my password".',
    'login.emailOuSenhaIncorretos': 'Incorrect email or password.',
    'login.contaCriada': 'Account created! Check your email to confirm before signing in.',
    'login.linkResetEnviado': 'We sent a password reset link to your email.',

    'sidebar.adminPanel': 'Admin Panel',
    'sidebar.logadoComo': 'Signed in as:',
    'sidebar.acesso': 'Access:',
    'sidebar.acessoCompleto': 'Full',
    'sidebar.acessoRestrito': 'Restricted',
    'sidebar.logout': '🚪 Log out',

    'nav.dashboard': '📊 Dashboard',
    'nav.agendamentos': '📅 Appointments',
    'nav.clientes': '👥 Clients',
    'nav.profissionais': '💈 Staff',
    'nav.caixa': '💰 Cash Register',
    'nav.comandas': '📋 Tickets',
    'nav.fidelidade': '🎁 Loyalty',
    'nav.ordem': '📍 Walk-in Queue',
    'nav.aniversariantes': '🎂 Birthdays',
    'nav.cadastros': '🗂️ Records',
    'nav.reincidentes': '⚠️ Repeat No-shows',
    'nav.mais': 'More',
    'nav.agendaCurta': 'Agenda',
    'nav.clientesCurta': 'Clients',

    'comum.salvar': 'Save',
    'comum.salvando': 'Saving...',
    'comum.cancelar': 'Cancel',
    'comum.adicionar': 'Add',
    'comum.deletar': 'Delete',
    'comum.remover': 'Remove',
    'comum.editar': 'Edit',
    'comum.carregando': '⏳ Loading...',
    'comum.acao': 'Action',
    'comum.acoes': 'Actions',
    'comum.status': 'Status',
    'comum.data': 'Date',
    'comum.hora': 'Time',
    'comum.cliente': 'Client',
    'comum.servico': 'Service',
    'comum.profissional': 'Staff',
    'comum.email': 'Email',
    'comum.telefone': 'Phone',
    'comum.valor': 'Amount',
    'comum.total': 'Total',
    'comum.detalhes': 'Details',
    'comum.ocultar': 'Hide',
    'comum.confirmar': 'Confirm',
    'comum.selecioneServico': 'Select a service',
    'comum.selecioneProfissional': 'Select a staff member',
    'comum.aberto': 'Open',
    'comum.fechado': 'Closed',

    'statusAg.AGENDADO': 'Scheduled',
    'statusAg.CONFIRMADO': 'Confirmed',
    'statusAg.REALIZADO': 'Completed',
    'statusAg.CANCELADO': 'Cancelled',
    'statusAg.NÃO_COMPARECEU': 'No-show',
    'statusAg.PREÇO_PENDENTE': 'Price pending',
    'statusAg.todos': 'All statuses',

    'dashboard.titulo': '📊 Dashboard',
    'dashboard.carregando': '⏳ Loading dashboard...',
    'dashboard.totalAgendamentos': '📅 Total Appointments',
    'dashboard.todosStatus': 'All statuses',
    'dashboard.confirmados': '✅ Confirmed',
    'dashboard.aguardando': 'Awaiting',
    'dashboard.realizados': '✓ Completed',
    'dashboard.completados': 'Completed',
    'dashboard.receitaTotal': '💰 Total Revenue',
    'dashboard.deServicosRealizados': 'From completed services',
    'dashboard.clientes': '👥 Clients',
    'dashboard.cadastrados': 'Registered',
    'dashboard.agendamentosPorStatus': 'Appointments by Status',
    'dashboard.agendamentosPorProfissional': 'Appointments by Staff',
    'dashboard.receita7Dias': 'Revenue - Last 7 Days',
    'dashboard.receitaLegenda': 'Revenue (¥)',
    'dashboard.agendamentosRecentes': 'Recent Appointments',
    'dashboard.erroBuscarDados': '❌ Error fetching data: {msg}',

    'agendamentos.titulo': '📅 Appointments',
    'agendamentos.novoAgendamento': 'New Appointment',
    'agendamentos.nomeCliente': "Client's Name",
    'agendamentos.emailCliente': "Client's Email",
    'agendamentos.emailClienteOpcional': "Client's Email (optional)",
    'agendamentos.telefoneOpcional': 'Phone',
    'agendamentos.modoEncaixe': '🔀 Fit-in Mode',
    'agendamentos.modoEncaixeAtivado': '(on — allows overlapping another time slot)',
    'agendamentos.selecioneParaVerHorarios': 'Select service, staff and date to see available times.',
    'agendamentos.conflito': '⚠️ Conflict:',
    'agendamentos.jaOcupadoNesseDia': 'Already booked that day: {lista}',
    'agendamentos.nenhumHorarioLivre': 'No free time slots that day for that staff member/service. Turn on Fit-in Mode to force a time.',
    'agendamentos.agendar': 'Book',
    'agendamentos.calendario': '📅 Calendar - {nome}',
    'agendamentos.anterior': '← Previous',
    'agendamentos.proximo': 'Next →',
    'agendamentos.listaDetalhada': '📋 Detailed List',
    'agendamentos.totalAgendamentos': 'Total: {n} appointments',
    'agendamentos.nenhumEncontrado': 'No appointments found',
    'agendamentos.diaSemana': 'Weekday',
    'agendamentos.preco': 'Price (¥)',
    'agendamentos.encaixeTag': '🔀 fit-in',
    'agendamentos.criadoComoEncaixe': 'Created as a fit-in',
    'agendamentos.confirmarDeletar': 'Are you sure you want to delete this appointment?',
    'agendamentos.preencherObrigatorios': '⚠️ Fill in all required fields!',
    'agendamentos.horarioIndisponivel': '⚠️ That time slot is no longer available. Choose another one from the list, or turn on Fit-in Mode to force it anyway.',
    'agendamentos.confirmarEncaixe': '⚠️ FIT-IN: this time ({horario}) overlaps the following appointment(s) of {prof}:\n\n{resumo}\n\nBy confirming, you take responsibility for resolving this conflict with the clients. Continue?',
    'agendamentos.criadoComSucesso': '✅ Appointment created successfully!',
    'agendamentos.erroAoCriar': '❌ Error creating appointment: {msg}',
    'agendamentos.statusAtualizado': '✅ Status updated!',
    'agendamentos.erroAtualizarStatus': '❌ Error updating status: {msg}',
    'agendamentos.deletado': '✅ Appointment deleted!',
    'agendamentos.erroDeletar': '❌ Error deleting: {msg}',
    'agendamentos.erroBuscar': '❌ Error fetching appointments: {msg}',
    'agendamentos.desconhecido': 'Unknown',
    'agendamentos.agendamentosDoDia': 'Appointments for {data}',
    'agendamentos.nenhumAgendamentoNoDia': 'No appointments that day.',
    'agendamentos.fecharModal': 'Close',
    'agendamentos.bloquearHorario': 'Block Time Off',
    'agendamentos.bloquearHorarioDescricao': 'Mark a period when the professional won\'t be available (doctor\'s appointment, time off, etc.) — that period becomes unavailable for new bookings.',
    'agendamentos.motivoOpcional': 'Reason (optional)',
    'agendamentos.criarBloqueio': 'Block',
    'agendamentos.bloqueioCriado': 'Time slot blocked successfully!',
    'agendamentos.erroCriarBloqueio': 'Error blocking time: {msg}',
    'agendamentos.horarioFimAntesInicio': 'End time must be after start time.',
    'agendamentos.confirmarDeletarBloqueio': 'Are you sure you want to remove this block?',
    'agendamentos.bloqueioDeletado': 'Block removed.',
    'agendamentos.erroDeletarBloqueio': 'Error removing block: {msg}',
    'agendamentos.bloqueiosAtivos': 'Scheduled blocks',
    'agendamentos.bloqueioTag': 'Blocked',
    'agendamentos.dataInicioLabel': 'Start date',
    'agendamentos.dataFimOpcionalLabel': 'End date (optional, for periods)',
    'agendamentos.diaInteiroLabel': 'Close the whole day (holiday, full day off)',
    'agendamentos.diaTodo': 'Closed (all day)',
    'agendamentos.bloqueioCriadoPeriodo': '{n} days blocked successfully!',
    'agendamentos.dataFimAntesInicio': 'End date must be on or after the start date.',
    'agendamentos.editarTooltip': 'Click to edit date/time',
    'agendamentos.editarAgendamento': 'Edit Appointment',
    'agendamentos.editarAgendamentoAviso': 'When saved, the client and the staff member automatically get an email about the time change.',
    'agendamentos.salvarAlteracao': 'Save change',
    'agendamentos.alteracaoSalva': 'Time updated! Client and staff member were notified by email.',
    'agendamentos.erroSalvarAlteracao': 'Error saving change: {msg}',
    'agendamentos.subDia': 'Day',
    'agendamentos.subSemana': 'Week',
    'agendamentos.subMes': 'Month',
    'agendamentos.subLista': 'List',
    'agendamentos.subBloqueios': 'Blocks',
    'agendamentos.livre': 'Free',
    'agendamentos.salaoFechadoNesseDia': 'The shop is closed that day.',
    'agendamentos.salaoFechadoNaSemana': 'The shop is closed the whole week in this period.',
    'agendamentos.fechado': 'Closed',
    'agendamentos.novoBtnFlutuante': 'New appointment',
    'agendamentos.escolhaData': 'Choose the date',
    'agendamentos.dataNascimento': 'Date of Birth (optional)',

    // Appointment Details View
    'agendamentos.verDetalhesTooltip': 'Tap to see appointment details',
    'agendamentos.detalhesAgendamento': 'Appointment Details',
    'agendamentos.valor': 'Price',
    'agendamentos.duracao': 'Duration',
    'agendamentos.duracaoMinutosSufixo': '{n} min',
    'agendamentos.duracaoInvalida': '⚠️ Enter a valid duration in minutes.',
    'agendamentos.dataHoraLabel': 'Date/Time',
    'agendamentos.criadoEm': 'Created at',
    'agendamentos.notas': 'Notes',
    'agendamentos.notasPlaceholder': 'Quick notes about this appointment...',
    'agendamentos.salvarNotas': 'Save notes',
    'agendamentos.notasSalvas': '✅ Notes saved!',
    'agendamentos.statusConfirmado': 'Confirmed',
    'agendamentos.statusPreferencia': 'Preference (client asked for this professional)',
    'agendamentos.statusAusente': 'No-show',
    'agendamentos.enviarLembrete': '📱 Send WhatsApp Reminder',
    'agendamentos.semTelefoneParaLembrete': '⚠️ This client has no phone number on file.',
    'agendamentos.mensagemLembrete': 'Hi {nome}! Just a reminder of your appointment at Kaizen Barber Shop on {data} at {hora} ({servico}). See you then! 💈',
    'agendamentos.prontuario': '📋 Record (attendance history)',
    'agendamentos.prontuarioTitulo': "Client's Record",
    'agendamentos.prontuarioVazio': 'No completed appointments yet.',
    'agendamentos.anamnese': '📝 Anamnesis (hair assessment)',
    'agendamentos.anamneseTitulo': "Client's Anamnesis",
    'agendamentos.anamnesePlaceholder': 'Hair history, allergies, preferences, assessment notes...',
    'agendamentos.salvarAnamnese': 'Save anamnesis',
    'agendamentos.anamneseSalva': '✅ Anamnesis saved!',
    'agendamentos.alterarParaEncaixe': '🔀 Change to Fit-in',
    'agendamentos.jaEhEncaixe': 'This appointment is already marked as a fit-in.',
    'agendamentos.confirmarAlterarEncaixe': 'Mark this appointment as a Fit-in (outside the standard schedule)?',
    'agendamentos.encaixeConvertidoTag': 'Converted to fit-in by Admin.',
    'agendamentos.erroSalvarCampo': '❌ Error saving: {msg}',
    'agendamentos.deletarAgendamento': '🗑️ Delete Appointment',

    // Cancellation with reason
    'agendamentos.cancelarAgendamento': '🚫 Cancel Appointment',
    'agendamentos.quemCancelou': 'Who cancelled?',
    'agendamentos.canceladoPor.cliente': 'Client',
    'agendamentos.canceladoPor.barbearia': 'Shop',
    'agendamentos.canceladoPorLabel': 'Cancelled by {quem}',
    'agendamentos.motivoCancelamento': 'Cancellation reason',
    'agendamentos.motivoCancelamentoPlaceholder': 'E.g.: client had a last-minute emergency...',
    'agendamentos.motivoCancelamentoObrigatorio': '⚠️ Describe the cancellation reason before confirming.',
    'agendamentos.confirmarCancelamento': 'Confirm cancellation',
    'agendamentos.cancelado': '✅ Appointment cancelled.',
    'agendamentos.erroCancelar': '❌ Error cancelling: {msg}',
    'agendamentos.avisoReincidenciaExplicacao': "Since there's less than 2h left, this counts as a last-minute cancellation — the client will show up on the Repeat Clients screen (More menu).",
    'agendamentos.avisoReincidencia': '⚠️ Heads up: {nome} has already had {n} last-minute cancellation(s). Check the Repeat Clients screen (More menu) to decide whether to keep serving them.',

    'menu.titulo': 'Menu',

    'clientes.titulo': '👥 Clients',
    'clientes.novoCliente': 'New Client',
    'clientes.nomeCliente': "Client's Name",
    'clientes.adicionarCliente': 'Add Client',
    'clientes.listaClientes': 'Client List',
    'clientes.nenhumCadastrado': 'No clients registered yet',
    'clientes.totalClientes': 'Total: {n} clients',
    'clientes.nome': 'Name',
    'clientes.primeiraVisita': 'First Visit',
    'clientes.totalAgendamentos': 'Total Appointments',
    'clientes.confirmados': 'Confirmed',
    'clientes.bloqueado': 'Blocked',
    'clientes.nomeEmailObrigatorios': '⚠️ Name and phone are required!',
    'clientes.dataNascimento': 'Date of Birth (optional)',
    'clientes.emailOpcional': 'Email (optional)',
    'clientes.adicionadoComSucesso': '✅ Client added successfully!',
    'clientes.confirmarDeletar': "Are you sure you want to delete this client? Their appointments will also be deleted!",
    'clientes.deletado': '✅ Client deleted!',
    'clientes.erroBuscar': '❌ Error fetching clients: {msg}',
    'clientes.erroAdicionar': '❌ Error adding client: {msg}',
    'clientes.erroDeletar': '❌ Error deleting client: {msg}',
    'clientes.editarCliente': 'Edit Client',
    'clientes.editadoComSucesso': '✅ Client updated successfully!',
    'clientes.erroEditar': '❌ Error updating client: {msg}',
    'clientes.mensagemWhatsapp': 'Hi {nome}! How are you? This is Kaizen Barber Shop. 💈',
    'clientes.buscarPlaceholder': 'Search client by name...',
    'clientes.nenhumEncontradoBusca': 'No client found with that name.',

    'profissionais.horarioSalao': '🕒 Shop Hours',
    'profissionais.horarioSalaoDesc': 'All staff follow this schedule by default. It is the single source used here and in the clients\' public booking page.',
    'profissionais.almoco': 'Lunch:',
    'profissionais.almocoTodosDias': '(every open day)',
    'profissionais.horarioEstendido': '📅 Extended Hours (holidays)',
    'profissionais.horarioEstendidoDesc': 'Use for extended holidays (e.g. Golden Week, Obon, New Year), when staff — like Gabriel, who usually opens earlier during the week — work from a different opening time than usual. While active, the opening time below applies to ALL staff, on the selected dates. Closing time and lunch break do not change.',
    'profissionais.ativado': 'On',
    'profissionais.desativado': 'Off',
    'profissionais.abertura': 'Opening',
    'profissionais.dataInicio': 'Start date',
    'profissionais.dataFim': 'End date',
    'profissionais.preencherDatas': 'Fill in the start and end date before turning it on.',
    'profissionais.salvo': 'Saved! The public booking page is now using this schedule.',
    'profissionais.erroSalvarHorario': "Couldn't save. Check whether the configuracoes_horario table exists in Supabase.",
    'profissionais.novoProfissional': 'New Staff Member',
    'profissionais.novoProfissionalDesc': 'This only adds a visual card here. For the staff member to actually appear in the public booking page and Admin (with schedule, commission, etc.), they need to be registered in Supabase and in config/profissionais.js.',
    'profissionais.nomeProfissional': "Staff Member's Name",
    'profissionais.especialidadesPlaceholder': 'Specialties (e.g. Haircuts, Beard)',
    'profissionais.adicionarProfissional': 'Add Staff Member',
    'profissionais.horarioLabel': 'Hours:',
    'profissionais.segueHorarioSalao': 'follows the shop hours (above)',
    'profissionais.comissao': 'Commission:',
    'profissionais.salvarComissao': 'Save Commission',
    'profissionais.comissaoNaoSalvo': '(not saved — visual entry only)',
    'profissionais.digiteNumeroValido': 'Enter a number between 0 and 100.',
    'profissionais.comissaoSalva': 'Saved!',
    'profissionais.erroSalvarComissao': "Couldn't save. Check whether the comissao_percentual column exists in the profissionais table.",

    'caixa.titulo': 'Cash Register - {dia}, {data}',
    'caixa.carregando': '⏳ Loading cash register...',
    'caixa.statusCaixa': 'Register Status',
    'caixa.aberto': '✅ OPEN',
    'caixa.fechado': '❌ CLOSED',
    'caixa.saldoInicialPlaceholder': 'Opening Balance (¥)',
    'caixa.reabrirCaixa': 'Reopen Register',
    'caixa.abrirCaixa': 'Open Register',
    'caixa.fecharCaixa': 'Close Register',
    'caixa.resumoDia': "Day's Summary",
    'caixa.saldoInicial': 'Opening Balance:',
    'caixa.entradas': 'Income:',
    'caixa.saidas': 'Expenses:',
    'caixa.saldoFinal': 'Closing Balance:',
    'caixa.novaMovimentacao': 'New Manual Entry',
    'caixa.entrada': 'Income',
    'caixa.saida': 'Expense',
    'caixa.descricaoPlaceholder': 'Description',
    'caixa.valorPlaceholder': 'Amount (¥)',
    'caixa.movimentacoesHoje': "Today's Entries",
    'caixa.nenhumaMovimentacao': 'No entries yet today',
    'caixa.tipo': 'Type',
    'caixa.descricao': 'Description',
    'caixa.entradaTag': '➕ Income',
    'caixa.saidaTag': '➖ Expense',
    'caixa.comanda': '(ticket)',
    'caixa.historicoDias': '📅 Day History (last 90 days)',
    'caixa.nenhumDiaRegistrado': 'No register days recorded yet',
    'caixa.semMovimentacoesNesseDia': 'No entries on this day.',
    'caixa.movimentoMes': '📆 Monthly Activity',
    'caixa.movimentoLiquido': 'Net Movement:',
    'caixa.comissaoPorProfissional': '💈 Commission by Staff',
    'caixa.semanaAtual': 'Current week ({inicio} to {fim})',
    'caixa.mesSelecionado': 'Selected month ({mes})',
    'caixa.faturado': 'Billed',
    'caixa.comissaoPercentual': 'Commission %',
    'caixa.comissaoDevida': 'Commission Owed',
    'caixa.comissaoDefinidaEm': "Each staff member's commission % is set in the Staff tab.",
    'caixa.confirmarFechar': "Close today's register? After this, no new tickets can be closed today without reopening it.",
    'caixa.confirmarRemoverMov': 'Remove this manual register entry?',
    'caixa.erroCarregar': '❌ Error loading register: {msg}',
    'caixa.erroCarregarMes': '❌ Error loading the month: {msg}',
    'caixa.erroAbrir': '❌ Error opening register: {msg}',
    'caixa.erroFechar': '❌ Error closing register: {msg}',
    'caixa.erroAdicionarMov': '❌ Error adding entry: {msg}',
    'caixa.erroRemoverMov': '❌ Error removing: {msg}',

    'comandas.titulo': '📋 Tickets of the Day - {dia}, {data}',
    'comandas.statusCaixa': 'Register Status',
    'comandas.abraCaixaAviso': 'Open the register on the Cash Register tab to close tickets or add walk-in services.',
    'comandas.totalRealizadoHoje': 'Total Completed Today',
    'comandas.atendimentos': 'Services:',
    'comandas.comandasAbertas': "🕓 Open Tickets (today's appointments)",
    'comandas.nenhumaComandaAberta': 'No open tickets for today',
    'comandas.fechar': '✅ Close',
    'comandas.lancarAvulso': 'Add Walk-in Service',
    'comandas.adicionarServico': 'Add Service',
    'comandas.selecioneProfissional': 'Select staff member',
    'comandas.servicosRealizadosHoje': "📊 Services Completed Today",
    'comandas.nenhumRealizadoAinda': 'No services completed yet today',
    'comandas.jaLancadosNoCaixa': "Already recorded in today's register — to correct an amount, adjust it directly in the Cash Register tab.",
    'comandas.caixaNaoAberto': "⚠️ Today's register hasn't been opened yet. Go to the Cash Register tab and open it before closing tickets.",
    'comandas.caixaNaoAbertoAvulso': "⚠️ Today's register hasn't been opened yet. Go to the Cash Register tab and open it before adding walk-in services.",
    'comandas.fecharPrompt': 'Close "{servico}" for {cliente} ({profissional}).\nFinal amount (¥):',
    'comandas.valorInvalido': '⚠️ Invalid amount.',
    'comandas.fechadaComSucesso': '✅ Ticket closed and recorded in the register!',
    'comandas.erroFechar': '❌ Error closing ticket: {msg}',
    'comandas.preencherTodosCampos': '⚠️ Fill in all fields!',
    'comandas.servicoOuProfInvalido': '⚠️ Invalid service or staff member.',
    'comandas.lancadaComSucesso': '✅ Service added to the ticket and the register!',
    'comandas.erroAdicionar': '❌ Error adding: {msg}',
    'comandas.erroBuscar': '❌ Error fetching tickets: {msg}',

    'fidelidade.titulo': '🎁 Loyalty Program',
    'fidelidade.totalPontos': '📊 Total Points',
    'fidelidade.emTodaBase': 'Across the whole client base',
    'fidelidade.clientesAtivos': '👥 Active Clients',
    'fidelidade.comAgendamentos': 'With appointments',
    'fidelidade.descontosResgatados': '💰 Discounts Redeemed',
    'fidelidade.valorTotalResgatado': 'Total amount redeemed',
    'fidelidade.regrasPrograma': 'ℹ️ Program Rules',
    'fidelidade.regra1': '✅ 2 points per completed service',
    'fidelidade.regra2': '✅ 10 points = ¥500 discount',
    'fidelidade.regra3': '✅ Valid for 3 months',
    'fidelidade.regra4': '✅ Non-transferable',
    'fidelidade.clientesSaldoPontos': '👥 Clients - Points Balance',
    'fidelidade.buscarClientePlaceholder': 'Search client by name...',
    'fidelidade.nenhumEncontrado': 'No clients found',
    'fidelidade.dataInscricao': 'Signup Date',
    'fidelidade.agendamentos': 'Appointments',
    'fidelidade.pontosDisponiveis': 'Available Points',
    'fidelidade.pontosResgatar': 'Points to Redeem',
    'fidelidade.descontoIene': 'Discount (¥)',
    'fidelidade.ativo': '✅ Active',
    'fidelidade.semPontos': '⚪ No points',
    'fidelidade.comoFunciona': '📋 How the Program Works',
    'fidelidade.objetivo': '🎯 Goal:',
    'fidelidade.objetivoTexto': 'Reward loyal clients with discounts on future services',
    'fidelidade.pontosLabel': '⭐ Points:',
    'fidelidade.pontosTexto': 'Client earns 2 points for each completed service',
    'fidelidade.resgate': '💳 Redemption:',
    'fidelidade.resgateTexto': 'For every 10 points accumulated, the client earns a ¥500 discount',
    'fidelidade.validade': '⏰ Validity:',
    'fidelidade.validadeTexto': 'Points are valid for 3 months from the service date',
    'fidelidade.intransferivel': '🔒 Non-transferable:',
    'fidelidade.intransferivelTexto': 'Points cannot be transferred between clients',
    'fidelidade.rastreamento': '📊 Tracking:',
    'fidelidade.rastreamentoTexto': 'Client can view their balance on the loyalty page',
    'fidelidade.erroBuscar': '❌ Error fetching clients: {msg}',

    'ordem.titulo': 'Walk-in Queue',
    'ordem.bloqueioAtivoHoje': '🚫 Active Block Today',
    'ordem.motivo': 'Reason:',
    'ordem.tipo': 'Type:',
    'ordem.diaInteiro': 'Full Day',
    'ordem.periodo': 'Period',
    'ordem.agendamentosBloqueados': '⚠️ Appointments blocked! Walk-in queue only.',
    'ordem.bloquearDiaPeriodo': 'Block Day/Period',
    'ordem.periodoManha': 'Period (Morning)',
    'ordem.periodoTarde': 'Period (Afternoon)',
    'ordem.periodoNoite': 'Period (Evening)',
    'ordem.motivoPlaceholder': 'Reason (e.g. Holiday, Festival, High Traffic)',
    'ordem.bloquear': 'Block',
    'ordem.diasBloqueados': 'Blocked Days',
    'ordem.diaInteiroTag': '📅 Full Day',
    'ordem.periodoTag': '🕐 Period',
    'ordem.ativo': '🔒 Active',
    'ordem.inativo': 'Inactive',
    'ordem.registrarChegada': 'Register Arrival',
    'ordem.nomeCliente': "Client's Name",
    'ordem.selecioneServico': 'Select service',
    'ordem.filaEspera': 'Waiting Line (Walk-in Order)',
    'ordem.ordem': 'Order',
    'ordem.horarioChegada': 'Arrival Time',
    'ordem.atendendo': '✅ Serving',
    'ordem.atendido': '✔️ Served',
    'ordem.aguardando': '⏳ Waiting',
    'ordem.atender': 'Serve',
    'ordem.finalizar': 'Finish',

    // Birthdays
    'aniversariantes.titulo': '🎂 Birthdays',
    'aniversariantes.aniversariantesDoMes': "This month's birthdays",
    'aniversariantes.proximos': 'Upcoming birthdays',
    'aniversariantes.nenhumEsteMes': 'No clients with a birthday this month (with a registered date).',
    'aniversariantes.nenhumCadastrado': 'No clients with a date of birth registered yet.',
    'aniversariantes.hoje': '🎉 Today!',
    'aniversariantes.diasFaltam': 'in {n} days',
    'aniversariantes.amanha': 'tomorrow',
    'aniversariantes.descontoDisponivel': '🎁 40% discount available until {data}',
    'aniversariantes.marcarUsado': 'Mark discount as used',
    'aniversariantes.confirmarUsarDesconto': "Mark this client's birthday discount as already used?",
    'aniversariantes.erroBuscar': '❌ Error fetching birthdays: {msg}',
    'aniversariantes.erroAtualizar': '❌ Error updating: {msg}',
    'aniversariantes.comoFunciona': 'ℹ️ Every day, the system checks whose birthday it is and automatically emails the client congratulating them and letting them know about the 40% discount (valid for 30 days). When the client comes back, apply the 40% when closing their ticket, then click "mark as used" here.',

    // Repeat No-shows (last-minute cancellations)
    'reincidentes.titulo': '⚠️ Repeat Clients',
    'reincidentes.comoFunciona': 'ℹ️ This shows every client with a last-minute cancellation (less than 2h notice) recorded by the Admin. From {n} occurrences the card is highlighted in red — a sign to consider whether it\'s worth continuing to serve them. The "Block" button only sets a warning flag; it does not yet prevent a new booking by itself.',
    'reincidentes.nenhum': 'No repeat clients so far. 🎉',
    'reincidentes.ocorrencias': '{n} last-minute cancellation(s)',
    'reincidentes.bloqueado': 'Blocked',
    'reincidentes.bloquear': 'Block client',
    'reincidentes.desbloquear': 'Unblock client',
    'reincidentes.confirmarBloquear': 'Mark {nome} as blocked?',
    'reincidentes.confirmarDesbloquear': 'Remove the block from {nome}?',
    'reincidentes.erroAtualizar': '❌ Error updating: {msg}',

    // Real-time notifications (toast + push)
    'notificacoes.novoAgendamento': 'New appointment',
    'notificacoes.novoAgendamentoCorpo': '{cliente} booked {servico} at {hora} with {profissional}.',
    'notificacoes.agendamentoCancelado': 'Appointment cancelled',
    'notificacoes.agendamentoCanceladoCorpo': '{cliente} cancelled {servico} at {hora} with {profissional}.',
    'notificacoes.ativarSom': 'Turn on notification sound',
    'notificacoes.desativarSom': 'Mute notifications',
    'notificacoes.push.titulo': 'Phone notifications',
    'notificacoes.push.descricao': 'Get an alert on your phone whenever someone books or cancels an appointment, even with the app closed.',
    'notificacoes.push.ativar': 'Enable notifications on this device',
    'notificacoes.push.ativando': 'Enabling...',
    'notificacoes.push.ativado': '✅ Notifications enabled on this device.',
    'notificacoes.push.desativar': 'Disable on this device',
    'notificacoes.push.naoSuportado': 'This browser does not support push notifications.',
    'notificacoes.push.permissaoNegada': '⚠️ You blocked notifications for this site. Enable them in your browser/phone settings.',
    'notificacoes.push.erro': '❌ Error enabling notifications: {msg}',

    // Records (Services / Products / Packages)
    'cadastros.titulo': '🗂️ Records',
    'cadastros.servicos.titulo': 'Services',
    'cadastros.servicos.subtitulo': 'Register services and make them available for booking',
    'cadastros.produtos.titulo': 'Products',
    'cadastros.produtos.subtitulo': 'Check your products and stock quantity',
    'cadastros.pacotes.titulo': 'Packages',
    'cadastros.pacotes.subtitulo': 'View your package sales',
    'cadastros.pacotes.meusPacotes': 'My Packages',
    'cadastros.pacotes.meusPacotesSubtitulo': 'Packages available for sale',
    'cadastros.pacotes.vendaPacotes': 'Package Sales',
    'cadastros.pacotes.vendaPacotesSubtitulo': 'History of packages sold to clients',
    'cadastros.buscarPlaceholder': 'Search by name',
    'cadastros.novoServico': 'New Service',
    'cadastros.novoProduto': 'New Product',
    'cadastros.novoPacote': 'New Package',
    'cadastros.registrarVenda': 'Register Sale',
    'cadastros.novoItem': 'New Record',
    'cadastros.editarItem': 'Edit Record',
    'cadastros.nomeCampo': 'Name',
    'cadastros.descricaoCampo': 'Description',
    'cadastros.precoCampo': 'Price (¥)',
    'cadastros.duracaoCampo': 'Duration (minutes)',
    'cadastros.estoqueCampo': 'Stock quantity',
    'cadastros.sessoesCampo': 'Number of sessions (leave blank = unlimited)',
    'cadastros.validadeCampo': 'Validity (days)',
    'cadastros.clienteCampo': "Client's Name",
    'cadastros.sessoesRestantesCampo': 'Sessions remaining (leave blank = unlimited)',
    'cadastros.ativoCampo': 'Active',
    'cadastros.nomeObrigatorio': '⚠️ Fill in the name before saving.',
    'cadastros.confirmarRemover': 'Are you sure you want to remove this record?',
    'cadastros.nenhumEncontrado': 'No results found.',
    'cadastros.inativo': 'inactive',
    'cadastros.semEstoque': 'Out of stock',
    'cadastros.estoqueUnidades': '{n} in stock',
    'cadastros.sessoesIlimitadas': 'Unlimited',
    'cadastros.sessoesRestantesLabel': '{n} sessions',
    'cadastros.validadeDiasLabel': 'valid {n} days',
    'cadastros.imagemCampo': 'Illustrative image',
    'cadastros.erroCarregarServicos': '❌ Error loading services: {msg}',
    'cadastros.servicoSalvo': '✅ Service saved! It already shows on the public site and the Agenda.',
    'cadastros.erroSalvarServico': '❌ Error saving service: {msg}',
    'cadastros.confirmarDesativarServico': "Deactivate this service? It stops showing on the public site and Admin, but the history of appointments already made with it is kept.",
    'cadastros.confirmarReativarServico': 'Reactivate this service? It shows again on the public site and Admin.',
    'cadastros.erroCarregarProdutos': '❌ Error loading products: {msg}',
    'cadastros.produtoSalvo': '✅ Product saved!',
    'cadastros.erroSalvarProduto': '❌ Error saving product: {msg}',
    'cadastros.confirmarDesativarProduto': 'Deactivate this product? It will be marked as unavailable.',
    'cadastros.confirmarReativarProduto': 'Reactivate this product?',
    'cadastros.erroCarregarPacotes': '❌ Error loading packages: {msg}',
    'cadastros.pacoteSalvo': '✅ Package saved! It already shows on the public site.',
    'cadastros.erroSalvarPacote': '❌ Error saving package: {msg}',
    'cadastros.confirmarDesativarPacote': 'Deactivate this package? It stops showing on the public site.',
    'cadastros.confirmarReativarPacote': 'Reactivate this package? It shows again on the public site.',
  },

  ja: {
    'login.tituloLogin': '管理者ログイン',
    'login.tituloCadastro': 'アカウント作成',
    'login.subtituloLogin': 'アカウントのメールとパスワードでログインしてください。',
    'login.subtituloCadastro': '新規アカウントは制限付きアクセスから始まります。必要な場合はフルアクセスへの昇格を依頼してください。',
    'login.nome': 'お名前',
    'login.email': 'メールアドレス',
    'login.senha': 'パスワード',
    'login.aguarde': 'お待ちください...',
    'login.entrar': 'ログイン',
    'login.criarConta': 'アカウント作成',
    'login.esqueciSenha': 'パスワードをお忘れですか',
    'login.criarUmaConta': 'アカウントを作成する',
    'login.jaTenhoConta': 'すでにアカウントをお持ちです',
    'login.voltarPublico': '公開サイトに戻る',
    'login.carregando': '読み込み中...',
    'login.digiteEmailPrimeiro': '先に上のメールアドレスを入力してから「パスワードをお忘れですか」をクリックしてください。',
    'login.emailOuSenhaIncorretos': 'メールアドレスまたはパスワードが間違っています。',
    'login.contaCriada': 'アカウントを作成しました！ログイン前にメールで確認してください。',
    'login.linkResetEnviado': 'パスワード再設定用のリンクをメールで送信しました。',

    'sidebar.adminPanel': '管理パネル',
    'sidebar.logadoComo': 'ログイン中:',
    'sidebar.acesso': 'アクセス権:',
    'sidebar.acessoCompleto': 'フル',
    'sidebar.acessoRestrito': '制限付き',
    'sidebar.logout': '🚪 ログアウト',

    'nav.dashboard': '📊 ダッシュボード',
    'nav.agendamentos': '📅 予約',
    'nav.clientes': '👥 顧客',
    'nav.profissionais': '💈 スタッフ',
    'nav.caixa': '💰 レジ',
    'nav.comandas': '📋 伝票',
    'nav.fidelidade': '🎁 ポイント制度',
    'nav.ordem': '📍 順番待ち',
    'nav.aniversariantes': '🎂 誕生日',
    'nav.cadastros': '🗂️ 登録管理',
    'nav.reincidentes': '⚠️ 常習キャンセル',
    'nav.mais': 'もっと',
    'nav.agendaCurta': '予約表',
    'nav.clientesCurta': '顧客',

    'comum.salvar': '保存',
    'comum.salvando': '保存中...',
    'comum.cancelar': 'キャンセル',
    'comum.adicionar': '追加',
    'comum.deletar': '削除',
    'comum.remover': '削除',
    'comum.editar': '編集',
    'comum.carregando': '⏳ 読み込み中...',
    'comum.acao': '操作',
    'comum.acoes': '操作',
    'comum.status': 'ステータス',
    'comum.data': '日付',
    'comum.hora': '時間',
    'comum.cliente': '顧客',
    'comum.servico': 'サービス',
    'comum.profissional': 'スタッフ',
    'comum.email': 'メール',
    'comum.telefone': '電話番号',
    'comum.valor': '金額',
    'comum.total': '合計',
    'comum.detalhes': '詳細',
    'comum.ocultar': '非表示',
    'comum.confirmar': '確認',
    'comum.selecioneServico': 'サービスを選択',
    'comum.selecioneProfissional': 'スタッフを選択',
    'comum.aberto': '営業中',
    'comum.fechado': '休業中',

    'statusAg.AGENDADO': '予約済み',
    'statusAg.CONFIRMADO': '確定',
    'statusAg.REALIZADO': '完了',
    'statusAg.CANCELADO': 'キャンセル',
    'statusAg.NÃO_COMPARECEU': '無断キャンセル',
    'statusAg.PREÇO_PENDENTE': '料金未確定',
    'statusAg.todos': 'すべてのステータス',

    'dashboard.titulo': '📊 ダッシュボード',
    'dashboard.carregando': '⏳ ダッシュボードを読み込み中...',
    'dashboard.totalAgendamentos': '📅 予約合計',
    'dashboard.todosStatus': 'すべてのステータス',
    'dashboard.confirmados': '✅ 確定',
    'dashboard.aguardando': '待機中',
    'dashboard.realizados': '✓ 完了',
    'dashboard.completados': '完了',
    'dashboard.receitaTotal': '💰 総売上',
    'dashboard.deServicosRealizados': '完了したサービスより',
    'dashboard.clientes': '👥 顧客',
    'dashboard.cadastrados': '登録数',
    'dashboard.agendamentosPorStatus': 'ステータス別予約数',
    'dashboard.agendamentosPorProfissional': 'スタッフ別予約数',
    'dashboard.receita7Dias': '売上 - 直近7日間',
    'dashboard.receitaLegenda': '売上 (¥)',
    'dashboard.agendamentosRecentes': '最近の予約',
    'dashboard.erroBuscarDados': '❌ データの取得エラー: {msg}',

    'agendamentos.titulo': '📅 予約',
    'agendamentos.novoAgendamento': '新規予約',
    'agendamentos.nomeCliente': '顧客名',
    'agendamentos.emailCliente': '顧客のメールアドレス',
    'agendamentos.emailClienteOpcional': '顧客のメールアドレス（任意）',
    'agendamentos.telefoneOpcional': '電話番号',
    'agendamentos.modoEncaixe': '🔀 割り込みモード',
    'agendamentos.modoEncaixeAtivado': '(オン — 他の予約時間との重複を許可)',
    'agendamentos.selecioneParaVerHorarios': 'サービス、スタッフ、日付を選択すると空き時間が表示されます。',
    'agendamentos.conflito': '⚠️ 重複:',
    'agendamentos.jaOcupadoNesseDia': 'その日はすでに予約済み: {lista}',
    'agendamentos.nenhumHorarioLivre': 'そのスタッフ・サービスでは空き時間がありません。割り込みモードをオンにすると強制的に予約できます。',
    'agendamentos.agendar': '予約する',
    'agendamentos.calendario': '📅 カレンダー - {nome}',
    'agendamentos.anterior': '← 前へ',
    'agendamentos.proximo': '次へ →',
    'agendamentos.listaDetalhada': '📋 詳細リスト',
    'agendamentos.totalAgendamentos': '合計: {n} 件の予約',
    'agendamentos.nenhumEncontrado': '予約が見つかりません',
    'agendamentos.diaSemana': '曜日',
    'agendamentos.preco': '料金 (¥)',
    'agendamentos.encaixeTag': '🔀 割り込み',
    'agendamentos.criadoComoEncaixe': '割り込みとして作成',
    'agendamentos.confirmarDeletar': 'この予約を削除してもよろしいですか？',
    'agendamentos.preencherObrigatorios': '⚠️ 必須項目をすべて入力してください！',
    'agendamentos.horarioIndisponivel': '⚠️ その時間はもう空いていません。リストから別の時間を選ぶか、割り込みモードをオンにして強制してください。',
    'agendamentos.confirmarEncaixe': '⚠️ 割り込み: この時間（{horario}）は{prof}の以下の予約と重なります:\n\n{resumo}\n\n確認すると、この重複について顧客との調整の責任を負うことになります。続けますか？',
    'agendamentos.criadoComSucesso': '✅ 予約を作成しました！',
    'agendamentos.erroAoCriar': '❌ 予約作成エラー: {msg}',
    'agendamentos.statusAtualizado': '✅ ステータスを更新しました！',
    'agendamentos.erroAtualizarStatus': '❌ ステータス更新エラー: {msg}',
    'agendamentos.deletado': '✅ 予約を削除しました！',
    'agendamentos.erroDeletar': '❌ 削除エラー: {msg}',
    'agendamentos.erroBuscar': '❌ 予約の取得エラー: {msg}',
    'agendamentos.desconhecido': '不明',
    'agendamentos.agendamentosDoDia': '{data}の予約',
    'agendamentos.nenhumAgendamentoNoDia': 'その日の予約はありません。',
    'agendamentos.fecharModal': '閉じる',
    'agendamentos.bloquearHorario': '時間をブロック',
    'agendamentos.bloquearHorarioDescricao': '担当者が対応できない時間帯(通院、休みなど)を設定します。その時間帯は新規予約ができなくなります。',
    'agendamentos.motivoOpcional': '理由(任意)',
    'agendamentos.criarBloqueio': 'ブロックする',
    'agendamentos.bloqueioCriado': '時間帯をブロックしました!',
    'agendamentos.erroCriarBloqueio': 'ブロックの作成エラー: {msg}',
    'agendamentos.horarioFimAntesInicio': '終了時刻は開始時刻より後にしてください。',
    'agendamentos.confirmarDeletarBloqueio': 'このブロックを削除してもよろしいですか?',
    'agendamentos.bloqueioDeletado': 'ブロックを削除しました。',
    'agendamentos.erroDeletarBloqueio': 'ブロックの削除エラー: {msg}',
    'agendamentos.bloqueiosAtivos': '予定されているブロック',
    'agendamentos.bloqueioTag': 'ブロック中',
    'agendamentos.dataInicioLabel': '開始日',
    'agendamentos.dataFimOpcionalLabel': '終了日(任意、期間指定用)',
    'agendamentos.diaInteiroLabel': '終日休業にする(祝日・全休)',
    'agendamentos.diaTodo': '休業(終日)',
    'agendamentos.bloqueioCriadoPeriodo': '{n}日間をブロックしました!',
    'agendamentos.dataFimAntesInicio': '終了日は開始日以降にしてください。',
    'agendamentos.editarTooltip': 'クリックして日時を編集',
    'agendamentos.editarAgendamento': '予約を編集',
    'agendamentos.editarAgendamentoAviso': '保存すると、お客様と担当スタッフに変更のお知らせメールが自動送信されます。',
    'agendamentos.salvarAlteracao': '変更を保存',
    'agendamentos.alteracaoSalva': '時間を変更しました!お客様とスタッフにメールで通知されました。',
    'agendamentos.erroSalvarAlteracao': '変更の保存エラー: {msg}',
    'agendamentos.subDia': '日',
    'agendamentos.subSemana': '週',
    'agendamentos.subMes': '月',
    'agendamentos.subLista': 'リスト',
    'agendamentos.subBloqueios': 'ブロック',
    'agendamentos.livre': '空き',
    'agendamentos.salaoFechadoNesseDia': 'この日は休業日です。',
    'agendamentos.salaoFechadoNaSemana': 'この期間は一週間ずっと休業日です。',
    'agendamentos.fechado': '休業',
    'agendamentos.novoBtnFlutuante': '新規予約',
    'agendamentos.escolhaData': '日付を選択',
    'agendamentos.dataNascimento': '生年月日（任意）',

    // 予約詳細画面
    'agendamentos.verDetalhesTooltip': 'タップして予約の詳細を見る',
    'agendamentos.detalhesAgendamento': '予約の詳細',
    'agendamentos.valor': '料金',
    'agendamentos.duracao': '所要時間',
    'agendamentos.duracaoMinutosSufixo': '{n}分',
    'agendamentos.duracaoInvalida': '⚠️ 有効な所要時間（分）を入力してください。',
    'agendamentos.dataHoraLabel': '日時',
    'agendamentos.criadoEm': '作成日時',
    'agendamentos.notas': '備考',
    'agendamentos.notasPlaceholder': 'この予約についてのメモ...',
    'agendamentos.salvarNotas': '備考を保存',
    'agendamentos.notasSalvas': '✅ 備考を保存しました！',
    'agendamentos.statusConfirmado': '確定',
    'agendamentos.statusPreferencia': '指名（この担当者を希望）',
    'agendamentos.statusAusente': '無断キャンセル',
    'agendamentos.enviarLembrete': '📱 WhatsAppでリマインダーを送信',
    'agendamentos.semTelefoneParaLembrete': '⚠️ この顧客には電話番号が登録されていません。',
    'agendamentos.mensagemLembrete': '{nome}様、Kaizen Barber Shopでのご予約のリマインダーです。{data} {hora}（{servico}）にお待ちしております！💈',
    'agendamentos.prontuario': '📋 カルテ（来店履歴）',
    'agendamentos.prontuarioTitulo': '顧客のカルテ',
    'agendamentos.prontuarioVazio': 'まだ完了した予約がありません。',
    'agendamentos.anamnese': '📝 問診票（毛髪状態の評価）',
    'agendamentos.anamneseTitulo': '顧客の問診票',
    'agendamentos.anamnesePlaceholder': '毛髪の履歴、アレルギー、好み、評価メモなど...',
    'agendamentos.salvarAnamnese': '問診票を保存',
    'agendamentos.anamneseSalva': '✅ 問診票を保存しました！',
    'agendamentos.alterarParaEncaixe': '🔀 割り込みに変更',
    'agendamentos.jaEhEncaixe': 'この予約はすでに割り込みとして登録されています。',
    'agendamentos.confirmarAlterarEncaixe': 'この予約を割り込み（通常の予約枠外）としてマークしますか？',
    'agendamentos.encaixeConvertidoTag': '管理者により割り込みに変更されました。',
    'agendamentos.erroSalvarCampo': '❌ 保存エラー: {msg}',
    'agendamentos.deletarAgendamento': '🗑️ 予約を削除',

    // 理由付きキャンセル
    'agendamentos.cancelarAgendamento': '🚫 予約をキャンセル',
    'agendamentos.quemCancelou': '誰がキャンセルしましたか？',
    'agendamentos.canceladoPor.cliente': '顧客',
    'agendamentos.canceladoPor.barbearia': '店舗',
    'agendamentos.canceladoPorLabel': '{quem}によるキャンセル',
    'agendamentos.motivoCancelamento': 'キャンセル理由',
    'agendamentos.motivoCancelamentoPlaceholder': '例：顧客に直前の急用が入った...',
    'agendamentos.motivoCancelamentoObrigatorio': '⚠️ 確定する前にキャンセル理由を入力してください。',
    'agendamentos.confirmarCancelamento': 'キャンセルを確定',
    'agendamentos.cancelado': '✅ 予約をキャンセルしました。',
    'agendamentos.erroCancelar': '❌ キャンセルエラー: {msg}',
    'agendamentos.avisoReincidenciaExplicacao': '予約時刻まで2時間未満のため、これは直前キャンセルとして扱われます — この顧客は「常習キャンセル」画面（Moreメニュー）に表示されます。',
    'agendamentos.avisoReincidencia': '⚠️ 注意：{nome}はすでに{n}回の直前キャンセルがあります。「常習キャンセル」画面（Moreメニュー）で今後の対応を検討してください。',

    'menu.titulo': 'メニュー',

    'clientes.titulo': '👥 顧客',
    'clientes.novoCliente': '新規顧客',
    'clientes.nomeCliente': '顧客名',
    'clientes.adicionarCliente': '顧客を追加',
    'clientes.listaClientes': '顧客リスト',
    'clientes.nenhumCadastrado': 'まだ顧客が登録されていません',
    'clientes.totalClientes': '合計: {n} 名の顧客',
    'clientes.nome': '名前',
    'clientes.primeiraVisita': '初回来店日',
    'clientes.totalAgendamentos': '予約合計',
    'clientes.confirmados': '確定済み',
    'clientes.bloqueado': 'ブロック済み',
    'clientes.nomeEmailObrigatorios': '⚠️ 名前と電話番号は必須です！',
    'clientes.dataNascimento': '生年月日（任意）',
    'clientes.emailOpcional': 'メールアドレス（任意）',
    'clientes.adicionadoComSucesso': '✅ 顧客を追加しました！',
    'clientes.confirmarDeletar': 'この顧客を削除してもよろしいですか？予約も削除されます！',
    'clientes.deletado': '✅ 顧客を削除しました！',
    'clientes.erroBuscar': '❌ 顧客の取得エラー: {msg}',
    'clientes.erroAdicionar': '❌ 顧客の追加エラー: {msg}',
    'clientes.erroDeletar': '❌ 顧客の削除エラー: {msg}',
    'clientes.editarCliente': '顧客を編集',
    'clientes.editadoComSucesso': '✅ 顧客情報を更新しました！',
    'clientes.erroEditar': '❌ 顧客の更新エラー: {msg}',
    'clientes.mensagemWhatsapp': '{nome}様、お元気ですか？Kaizen Barber Shopです。💈',
    'clientes.buscarPlaceholder': '名前で顧客を検索...',
    'clientes.nenhumEncontradoBusca': 'その名前の顧客は見つかりませんでした。',

    'profissionais.horarioSalao': '🕒 店舗営業時間',
    'profissionais.horarioSalaoDesc': '全スタッフはデフォルトでこの営業時間に従います。ここと公開予約ページで使われる唯一の情報源です。',
    'profissionais.almoco': '昼休憩:',
    'profissionais.almocoTodosDias': '(営業日すべて)',
    'profissionais.horarioEstendido': '📅 特別営業時間（祝日）',
    'profissionais.horarioEstendidoDesc': 'ゴールデンウィーク、お盆、お正月などの連休で、Gabrielのように普段より早く開店するスタッフがいる場合に使用します。有効にすると、以下の開店時間が選択した日付の全スタッフに適用されます。閉店時間と昼休憩は変わりません。',
    'profissionais.ativado': '有効',
    'profissionais.desativado': '無効',
    'profissionais.abertura': '開店時間',
    'profissionais.dataInicio': '開始日',
    'profissionais.dataFim': '終了日',
    'profissionais.preencherDatas': '有効にする前に開始日と終了日を入力してください。',
    'profissionais.salvo': '保存しました！公開予約ページも既にこの営業時間を使用しています。',
    'profissionais.erroSalvarHorario': '保存できませんでした。Supabaseにconfiguracoes_horarioテーブルが存在するか確認してください。',
    'profissionais.novoProfissional': '新規スタッフ',
    'profissionais.novoProfissionalDesc': 'ここではビジュアルカードが追加されるだけです。公開予約ページとAdminに実際に表示させる（営業時間、歩合率など）には、Supabaseとconfig/profissionais.jsに登録する必要があります。',
    'profissionais.nomeProfissional': 'スタッフ名',
    'profissionais.especialidadesPlaceholder': '得意分野（例：カット、ひげ）',
    'profissionais.adicionarProfissional': 'スタッフを追加',
    'profissionais.horarioLabel': '営業時間:',
    'profissionais.segueHorarioSalao': '店舗営業時間に従う（上記）',
    'profissionais.comissao': '歩合率:',
    'profissionais.salvarComissao': '歩合率を保存',
    'profissionais.comissaoNaoSalvo': '(未保存 — ビジュアル登録のみ)',
    'profissionais.digiteNumeroValido': '0から100の間の数字を入力してください。',
    'profissionais.comissaoSalva': '保存しました！',
    'profissionais.erroSalvarComissao': '保存できませんでした。profissionaisテーブルにcomissao_percentual列が存在するか確認してください。',

    'caixa.titulo': 'レジ - {dia}、{data}',
    'caixa.carregando': '⏳ レジを読み込み中...',
    'caixa.statusCaixa': 'レジの状態',
    'caixa.aberto': '✅ 営業中',
    'caixa.fechado': '❌ 締め済み',
    'caixa.saldoInicialPlaceholder': '開始残高 (¥)',
    'caixa.reabrirCaixa': 'レジを再開',
    'caixa.abrirCaixa': 'レジを開く',
    'caixa.fecharCaixa': 'レジを締める',
    'caixa.resumoDia': '本日のまとめ',
    'caixa.saldoInicial': '開始残高:',
    'caixa.entradas': '入金:',
    'caixa.saidas': '出金:',
    'caixa.saldoFinal': '最終残高:',
    'caixa.novaMovimentacao': '手動記録の追加',
    'caixa.entrada': '入金',
    'caixa.saida': '出金',
    'caixa.descricaoPlaceholder': '説明',
    'caixa.valorPlaceholder': '金額 (¥)',
    'caixa.movimentacoesHoje': '本日の記録',
    'caixa.nenhumaMovimentacao': '本日はまだ記録がありません',
    'caixa.tipo': '種類',
    'caixa.descricao': '説明',
    'caixa.entradaTag': '➕ 入金',
    'caixa.saidaTag': '➖ 出金',
    'caixa.comanda': '(伝票)',
    'caixa.historicoDias': '📅 日別履歴（過去90日）',
    'caixa.nenhumDiaRegistrado': 'まだレジの記録がありません',
    'caixa.semMovimentacoesNesseDia': 'この日は記録がありません。',
    'caixa.movimentoMes': '📆 月間の動き',
    'caixa.movimentoLiquido': '純増減:',
    'caixa.comissaoPorProfissional': '💈 スタッフ別歩合',
    'caixa.semanaAtual': '今週 ({inicio} 〜 {fim})',
    'caixa.mesSelecionado': '選択した月 ({mes})',
    'caixa.faturado': '売上',
    'caixa.comissaoPercentual': '歩合率 %',
    'caixa.comissaoDevida': '支払うべき歩合',
    'caixa.comissaoDefinidaEm': '各スタッフの歩合率は「スタッフ」タブで設定します。',
    'caixa.confirmarFechar': '本日のレジを締めますか？その後、再開しない限り本日新しい伝票を締めることはできません。',
    'caixa.confirmarRemoverMov': 'この手動レジ記録を削除しますか？',
    'caixa.erroCarregar': '❌ レジの読み込みエラー: {msg}',
    'caixa.erroCarregarMes': '❌ 月データの読み込みエラー: {msg}',
    'caixa.erroAbrir': '❌ レジを開くエラー: {msg}',
    'caixa.erroFechar': '❌ レジを締めるエラー: {msg}',
    'caixa.erroAdicionarMov': '❌ 記録の追加エラー: {msg}',
    'caixa.erroRemoverMov': '❌ 削除エラー: {msg}',

    'comandas.titulo': '📋 本日の伝票 - {dia}、{data}',
    'comandas.statusCaixa': 'レジの状態',
    'comandas.abraCaixaAviso': '伝票を締めたり、当日受付の施術を追加するには「レジ」タブでレジを開いてください。',
    'comandas.totalRealizadoHoje': '本日の完了合計',
    'comandas.atendimentos': '施術数:',
    'comandas.comandasAbertas': '🕓 未処理の伝票（本日の予約）',
    'comandas.nenhumaComandaAberta': '本日の未処理伝票はありません',
    'comandas.fechar': '✅ 締める',
    'comandas.lancarAvulso': '当日受付の施術を追加',
    'comandas.adicionarServico': 'サービスを追加',
    'comandas.selecioneProfissional': 'スタッフを選択',
    'comandas.servicosRealizadosHoje': '📊 本日完了したサービス',
    'comandas.nenhumRealizadoAinda': '本日はまだ完了したサービスがありません',
    'comandas.jaLancadosNoCaixa': '本日のレジにすでに記録済みです — 金額を修正する場合は「レジ」タブで直接調整してください。',
    'comandas.caixaNaoAberto': '⚠️ 本日のレジがまだ開いていません。「レジ」タブでレジを開いてから伝票を締めてください。',
    'comandas.caixaNaoAbertoAvulso': '⚠️ 本日のレジがまだ開いていません。「レジ」タブでレジを開いてから当日受付の施術を追加してください。',
    'comandas.fecharPrompt': '{cliente}様（{profissional}）の「{servico}」を締めます。\n最終金額 (¥):',
    'comandas.valorInvalido': '⚠️ 金額が無効です。',
    'comandas.fechadaComSucesso': '✅ 伝票を締めてレジに記録しました！',
    'comandas.erroFechar': '❌ 伝票を締めるエラー: {msg}',
    'comandas.preencherTodosCampos': '⚠️ すべての項目を入力してください！',
    'comandas.servicoOuProfInvalido': '⚠️ サービスまたはスタッフが無効です。',
    'comandas.lancadaComSucesso': '✅ 伝票とレジに施術を追加しました！',
    'comandas.erroAdicionar': '❌ 追加エラー: {msg}',
    'comandas.erroBuscar': '❌ 伝票の取得エラー: {msg}',

    'fidelidade.titulo': '🎁 ポイント制度',
    'fidelidade.totalPontos': '📊 合計ポイント',
    'fidelidade.emTodaBase': '全顧客の合計',
    'fidelidade.clientesAtivos': '👥 アクティブな顧客',
    'fidelidade.comAgendamentos': '予約あり',
    'fidelidade.descontosResgatados': '💰 交換済み割引',
    'fidelidade.valorTotalResgatado': '交換済み合計金額',
    'fidelidade.regrasPrograma': 'ℹ️ 制度のルール',
    'fidelidade.regra1': '✅ 施術完了ごとに2ポイント',
    'fidelidade.regra2': '✅ 10ポイント = ¥500割引',
    'fidelidade.regra3': '✅ 有効期限3ヶ月',
    'fidelidade.regra4': '✅ 譲渡不可',
    'fidelidade.clientesSaldoPontos': '👥 顧客 - ポイント残高',
    'fidelidade.buscarClientePlaceholder': '顧客名で検索...',
    'fidelidade.nenhumEncontrado': '顧客が見つかりません',
    'fidelidade.dataInscricao': '登録日',
    'fidelidade.agendamentos': '予約数',
    'fidelidade.pontosDisponiveis': '利用可能ポイント',
    'fidelidade.pontosResgatar': '交換可能ポイント',
    'fidelidade.descontoIene': '割引 (¥)',
    'fidelidade.ativo': '✅ 有効',
    'fidelidade.semPontos': '⚪ ポイントなし',
    'fidelidade.comoFunciona': '📋 制度の仕組み',
    'fidelidade.objetivo': '🎯 目的:',
    'fidelidade.objetivoTexto': '常連のお客様に今後のサービスの割引で還元します',
    'fidelidade.pontosLabel': '⭐ ポイント:',
    'fidelidade.pontosTexto': '施術完了ごとに2ポイント獲得',
    'fidelidade.resgate': '💳 交換:',
    'fidelidade.resgateTexto': '10ポイントたまるごとに¥500割引を獲得',
    'fidelidade.validade': '⏰ 有効期限:',
    'fidelidade.validadeTexto': 'ポイントは施術日から3ヶ月間有効です',
    'fidelidade.intransferivel': '🔒 譲渡不可:',
    'fidelidade.intransferivelTexto': 'ポイントは顧客間で譲渡できません',
    'fidelidade.rastreamento': '📊 確認方法:',
    'fidelidade.rastreamentoTexto': '顧客はポイント制度ページで残高を確認できます',
    'fidelidade.erroBuscar': '❌ 顧客の取得エラー: {msg}',

    'ordem.titulo': '順番待ち',
    'ordem.bloqueioAtivoHoje': '🚫 本日はブロック中',
    'ordem.motivo': '理由:',
    'ordem.tipo': '種類:',
    'ordem.diaInteiro': '終日',
    'ordem.periodo': '時間帯',
    'ordem.agendamentosBloqueados': '⚠️ 予約はブロックされています！順番待ちのみ受付。',
    'ordem.bloquearDiaPeriodo': '日/時間帯をブロック',
    'ordem.periodoManha': '時間帯（午前）',
    'ordem.periodoTarde': '時間帯（午後）',
    'ordem.periodoNoite': '時間帯（夜）',
    'ordem.motivoPlaceholder': '理由（例：祝日、フェスティバル、混雑）',
    'ordem.bloquear': 'ブロックする',
    'ordem.diasBloqueados': 'ブロック中の日',
    'ordem.diaInteiroTag': '📅 終日',
    'ordem.periodoTag': '🕐 時間帯',
    'ordem.ativo': '🔒 有効',
    'ordem.inativo': '無効',
    'ordem.registrarChegada': '来店を登録',
    'ordem.nomeCliente': '顧客名',
    'ordem.selecioneServico': 'サービスを選択',
    'ordem.filaEspera': '待機列（順番待ち）',
    'ordem.ordem': '順番',
    'ordem.horarioChegada': '来店時刻',
    'ordem.atendendo': '✅ 対応中',
    'ordem.atendido': '✔️ 対応済み',
    'ordem.aguardando': '⏳ 待機中',
    'ordem.atender': '対応する',
    'ordem.finalizar': '完了',

    // 誕生日
    'aniversariantes.titulo': '🎂 誕生日',
    'aniversariantes.aniversariantesDoMes': '今月の誕生日',
    'aniversariantes.proximos': '次の誕生日',
    'aniversariantes.nenhumEsteMes': '今月誕生日の顧客はいません（生年月日登録済みの中で）。',
    'aniversariantes.nenhumCadastrado': '生年月日が登録されている顧客がまだいません。',
    'aniversariantes.hoje': '🎉 今日！',
    'aniversariantes.diasFaltam': 'あと{n}日',
    'aniversariantes.amanha': '明日',
    'aniversariantes.descontoDisponivel': '🎁 {data}まで40%割引が利用可能',
    'aniversariantes.marcarUsado': '割引を使用済みにする',
    'aniversariantes.confirmarUsarDesconto': 'この顧客の誕生日割引を使用済みにしますか？',
    'aniversariantes.erroBuscar': '❌ 誕生日情報の取得エラー: {msg}',
    'aniversariantes.erroAtualizar': '❌ 更新エラー: {msg}',
    'aniversariantes.comoFunciona': 'ℹ️ 毎日、システムが誕生日の顧客を確認し、40%割引（30日間有効）のお知らせメールを自動送信します。顧客が来店したら会計時に40%を適用し、その後こちらで「使用済みにする」をクリックしてください。',

    // 常習キャンセル（直前キャンセル）
    'reincidentes.titulo': '⚠️ 常習キャンセル顧客',
    'reincidentes.comoFunciona': 'ℹ️ 管理者が記録した「直前キャンセル」（予約時刻の2時間未満前）がある顧客が表示されます。{n}回以上になるとカードが赤く強調表示されます — 今後の対応を検討するサインです。「ブロック」ボタンは警告の印を付けるだけで、まだ新規予約を自動的に防ぐものではありません。',
    'reincidentes.nenhum': '今のところ常習キャンセルの顧客はいません。🎉',
    'reincidentes.ocorrencias': '直前キャンセル {n}回',
    'reincidentes.bloqueado': 'ブロック済み',
    'reincidentes.bloquear': '顧客をブロック',
    'reincidentes.desbloquear': 'ブロックを解除',
    'reincidentes.confirmarBloquear': '{nome}をブロック済みにしますか？',
    'reincidentes.confirmarDesbloquear': '{nome}のブロックを解除しますか？',
    'reincidentes.erroAtualizar': '❌ 更新エラー: {msg}',

    // リアルタイム通知（トースト + プッシュ）
    'notificacoes.novoAgendamento': '新規予約',
    'notificacoes.novoAgendamentoCorpo': '{cliente}様が{hora}に{profissional}で{servico}を予約しました。',
    'notificacoes.agendamentoCancelado': '予約キャンセル',
    'notificacoes.agendamentoCanceladoCorpo': '{cliente}様が{hora}の{profissional}での{servico}をキャンセルしました。',
    'notificacoes.ativarSom': '通知音をオンにする',
    'notificacoes.desativarSom': '通知をミュートする',
    'notificacoes.push.titulo': 'スマホ通知',
    'notificacoes.push.descricao': 'アプリを閉じていても、予約や キャンセルがあったときにスマホに通知が届きます。',
    'notificacoes.push.ativar': 'この端末で通知を有効にする',
    'notificacoes.push.ativando': '有効にしています...',
    'notificacoes.push.ativado': '✅ この端末で通知が有効になりました。',
    'notificacoes.push.desativar': 'この端末で無効にする',
    'notificacoes.push.naoSuportado': 'このブラウザはプッシュ通知に対応していません。',
    'notificacoes.push.permissaoNegada': '⚠️ このサイトの通知がブロックされています。ブラウザ/端末の設定で許可してください。',
    'notificacoes.push.erro': '❌ 通知の有効化エラー: {msg}',

    // 登録管理（サービス・商品・パッケージ）
    'cadastros.titulo': '🗂️ 登録管理',
    'cadastros.servicos.titulo': 'サービス',
    'cadastros.servicos.subtitulo': 'サービスを登録して予約できるようにします',
    'cadastros.produtos.titulo': '商品',
    'cadastros.produtos.subtitulo': '商品と在庫数を確認します',
    'cadastros.pacotes.titulo': 'パッケージ',
    'cadastros.pacotes.subtitulo': 'パッケージの販売状況を確認します',
    'cadastros.pacotes.meusPacotes': 'マイパッケージ',
    'cadastros.pacotes.meusPacotesSubtitulo': '販売可能なパッケージ一覧',
    'cadastros.pacotes.vendaPacotes': 'パッケージ販売',
    'cadastros.pacotes.vendaPacotesSubtitulo': '顧客に販売したパッケージの履歴',
    'cadastros.buscarPlaceholder': '名前で検索',
    'cadastros.novoServico': '新規サービス',
    'cadastros.novoProduto': '新規商品',
    'cadastros.novoPacote': '新規パッケージ',
    'cadastros.registrarVenda': '販売を登録',
    'cadastros.novoItem': '新規登録',
    'cadastros.editarItem': '登録を編集',
    'cadastros.nomeCampo': '名前',
    'cadastros.descricaoCampo': '説明',
    'cadastros.precoCampo': '価格 (¥)',
    'cadastros.duracaoCampo': '所要時間（分）',
    'cadastros.estoqueCampo': '在庫数',
    'cadastros.sessoesCampo': '回数（空欄=無制限）',
    'cadastros.validadeCampo': '有効期限（日数）',
    'cadastros.clienteCampo': '顧客名',
    'cadastros.sessoesRestantesCampo': '残り回数（空欄=無制限）',
    'cadastros.ativoCampo': '有効',
    'cadastros.nomeObrigatorio': '⚠️ 保存する前に名前を入力してください。',
    'cadastros.confirmarRemover': 'この登録を削除してもよろしいですか？',
    'cadastros.nenhumEncontrado': '該当する結果がありません。',
    'cadastros.inativo': '無効',
    'cadastros.semEstoque': '在庫切れ',
    'cadastros.estoqueUnidades': '在庫 {n} 点',
    'cadastros.sessoesIlimitadas': '無制限',
    'cadastros.sessoesRestantesLabel': '残り{n}回',
    'cadastros.validadeDiasLabel': '有効期限{n}日',
    'cadastros.imagemCampo': 'イメージ画像',
    'cadastros.erroCarregarServicos': '❌ サービスの読み込みエラー: {msg}',
    'cadastros.servicoSalvo': '✅ サービスを保存しました！公開サイトと予約画面にすぐに反映されます。',
    'cadastros.erroSalvarServico': '❌ サービスの保存エラー: {msg}',
    'cadastros.confirmarDesativarServico': 'このサービスを無効にしますか？公開サイトと管理画面には表示されなくなりますが、過去の予約履歴は保持されます。',
    'cadastros.confirmarReativarServico': 'このサービスを再度有効にしますか？公開サイトと管理画面に再表示されます。',
    'cadastros.erroCarregarProdutos': '❌ 商品の読み込みエラー: {msg}',
    'cadastros.produtoSalvo': '✅ 商品を保存しました！',
    'cadastros.erroSalvarProduto': '❌ 商品の保存エラー: {msg}',
    'cadastros.confirmarDesativarProduto': 'この商品を無効にしますか？販売不可として表示されます。',
    'cadastros.confirmarReativarProduto': 'この商品を再度有効にしますか？',
    'cadastros.erroCarregarPacotes': '❌ パッケージの読み込みエラー: {msg}',
    'cadastros.pacoteSalvo': '✅ パッケージを保存しました！公開サイトにすぐに反映されます。',
    'cadastros.erroSalvarPacote': '❌ パッケージの保存エラー: {msg}',
    'cadastros.confirmarDesativarPacote': 'このパッケージを無効にしますか？公開サイトには表示されなくなります。',
    'cadastros.confirmarReativarPacote': 'このパッケージを再度有効にしますか？公開サイトに再表示されます。',
  },
};

export const traduzirAdmin = (idioma, chave, valores) => {
  const dict = TEXTOS[idioma] || TEXTOS[IDIOMA_ADMIN_PADRAO];
  let texto = dict[chave] ?? TEXTOS[IDIOMA_ADMIN_PADRAO][chave] ?? chave;
  if (valores) {
    Object.entries(valores).forEach(([k, v]) => {
      texto = texto.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
    });
  }
  return texto;
};
